In [1]:
#Establish required libraries

import sys
import types
import pandas as pd 
from botocore.client import Config
import ibm_boto3


import numpy as np
import pandas as pd
from pandas import Series, DataFrame, Index
from IPython.display import Image

def __iter__(self): return 0

import pandas as pd
import numpy as np 

class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

In [2]:
#Establish Libraries and connect to object storage
import sys
import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_e2f5521e5ce34913a7133599cf5a489b = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='xxxxxxxxxx',
    ibm_auth_endpoint="https://iam.ng.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_e2f5521e5ce34913a7133599cf5a489b.get_object(Bucket='tradepromotioncampaignevaluation-donotdelete-pr-jezovp3wjfejkl',Key='all products.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_1 = pd.read_csv(body)

df_data_1.info()

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 385636 entries, 0 to 385635
Data columns (total 72 columns):
Demo_Key                                    385636 non-null int64
Promo_ID                                    385636 non-null object
Promo_CPG_Name                              281228 non-null object
Promo_Name                                  385636 non-null object
Retailer_Promo_Contract_ID                  0 non-null float64
Retailer_Name                               385636 non-null object
Retailer_Store_ID                           385636 non-null object
Product_Unit_UPC                            385636 non-null object
Product_Group_ID                            385635 non-null object
Product_Brand                               385636 non-null object
Product_Brand_Category_Desc                 385636 non-null object
Product_Category                            385636 non-null object
Product_Sub_Category                        385636 non-null object
Product_Type                                385636 non-null object
Product_Unit_Description                    385636 non-null object
Retailer_Product_Base_Day_Unit_Volume       385636 non-null float64
Product_CPG_COGS_Price                      385636 non-null float64
Product_Unit_CPG_Retailer_Price             385636 non-null float64
Product_Unit_CPG_Retailer_Discount_Price    385636 non-null float64
Product_Promo_Trade_Investment_Per_Unit     385636 non-null float64
Product_Unit_Retailer_Markup_%              385636 non-null float64
Retailer_Product_Regular_Unit_Price         385636 non-null float64
TPP_Status                                  385636 non-null object
TPP_Discount_%                              385636 non-null float64
TPP_Unit_Sale_Price                         385636 non-null float64
TPP_Baseline_Unit_Volume                    385636 non-null float64
TPP_Start                                   385636 non-null object
TPP_End                                     385636 non-null object
TPP_Duration                                385636 non-null float64
TPP_Type                                    385636 non-null object
Product_Units_Per_Case                      385636 non-null float64
TPP_Baseline_Cases_Volume                   385636 non-null float64
TPP_Baseline_Cost                           385636 non-null float64
TPP_Baseline_Sales_Revenue                  385636 non-null float64
TPP_Baseline_Retailer_Profit                385636 non-null float64
TPP_Baseline_ROI                            385636 non-null float64
TPP_ACV%                                    385635 non-null float64
TPP_Budget                                  385636 non-null float64
TPP_Incremental_Unit_%                      385636 non-null float64
TPP_Incremental_Unit_Volume                 385636 non-null float64
TPP_Incremental_Cases                       385636 non-null float64
TPP_Incremental_Revenue                     385636 non-null float64
TPP_Incremental_Costs                       385636 non-null float64
TPP_Units_Ship                              385636 non-null float64
TPP_Cases_Ship                              385636 non-null float64
TPP_Fixed_Fees                              385636 non-null float64
TPP_Incremental_Variable_Fees               385636 non-null float64
TPP_Total_Fees                              385636 non-null float64
TPP_Comments                                0 non-null float64
TPP_Retailer_ROI%                           385636 non-null float64
TPP_CPG_ROI%                                385636 non-null float64
TPPA_Type                                   385636 non-null object
TPPA_Cost                                   385636 non-null float64
TPPA_Unit_Sale_Price                        385636 non-null float64
TPPA_Discount                               385636 non-null float64
TPPA_Fixed_Fees                             385636 non-null float64
TPPA_Variable_Fees                          385636 non-null float64
TPPA_Total_Fees                             385636 non-null float64
TPPA_Units_Sold                             385636 non-null float64
TPPA_Cases_Sold                             385636 non-null float64
TPPA_Incremental_Cases_Sold                 385636 non-null float64
TPPA_Incremental_Unit_Volume                385636 non-null float64
TPPA_Incremental_Cost                       385636 non-null float64
TPPA_Incremental_Revenue                    385636 non-null float64
TPPA_Incremental_Unit_%                     385636 non-null float64
TPPA_Days_Payment_Due                       385636 non-null float64
TPPA_Days_Payment_Late_Outstanding          385636 non-null float64
TPPA_Payment+Compliance_Calc                385636 non-null object
TPPA_Payment_In_Compliance                  385636 non-null object
TPPA_%ACV                                   385635 non-null float64
TPPA_Retailer_ROI%                          385636 non-null float64
TPPA_CPG_ROI%                               385636 non-null float64
dtypes: float64(51), int64(1), object(20)
memory usage: 211.8+ MB

In [3]:
#select the fields you need
df_price_elasticity = df_data_1[['Promo_ID','Promo_Name','Retailer_Name','Retailer_Store_ID','Product_Category',
                                 'Product_Sub_Category',
                             'Product_Unit_UPC','Product_Group_ID','Product_Brand','Product_Brand_Category_Desc',
                              'Product_Unit_Description','Retailer_Product_Base_Day_Unit_Volume',
                              'TPP_Unit_Sale_Price','Retailer_Product_Regular_Unit_Price','TPP_Incremental_Cases',
                             'TPP_Baseline_Cases_Volume','TPP_Type','TPP_Start','TPP_End','Product_Units_Per_Case','Product_CPG_COGS_Price']]

In [4]:
#Visually inspect the different products in the table
df_price_elasticity.Product_Sub_Category.value_counts(dropna = False).sort_index()

Cereal         67360
Cleaners       30312
Ice Cream      47152
Trail Mix      74096
Vegetables    116196
Yogurt         50520
Name: Product_Sub_Category, dtype: int64

In [5]:
df_price_elasticity.shape

(385636, 21)

In [6]:
#De-Dup the file
df_price_elasticity=df_price_elasticity.drop_duplicates(subset=['Promo_ID','Retailer_Store_ID','Product_Unit_UPC'], keep='first', inplace=False)
df_price_elasticity.shape

(385636, 21)

In [7]:
#remove all products but the one we us

df_price_elasticity=df_price_elasticity[df_price_elasticity['Product_Sub_Category'] =='Cleaners']
df_price_elasticity.shape

(30312, 21)

In [8]:
#create a new field for size
df_price_elasticity['SIZE']=pd.DataFrame(df_price_elasticity['Product_Group_ID'].str[-2:])

In [9]:
df_price_elasticity.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30312 entries, 355324 to 385635
Data columns (total 22 columns):
Promo_ID                                 30312 non-null object
Promo_Name                               30312 non-null object
Retailer_Name                            30312 non-null object
Retailer_Store_ID                        30312 non-null object
Product_Category                         30312 non-null object
Product_Sub_Category                     30312 non-null object
Product_Unit_UPC                         30312 non-null object
Product_Group_ID                         30312 non-null object
Product_Brand                            30312 non-null object
Product_Brand_Category_Desc              30312 non-null object
Product_Unit_Description                 30312 non-null object
Retailer_Product_Base_Day_Unit_Volume    30312 non-null float64
TPP_Unit_Sale_Price                      30312 non-null float64
Retailer_Product_Regular_Unit_Price      30312 non-null float64
TPP_Incremental_Cases                    30312 non-null float64
TPP_Baseline_Cases_Volume                30312 non-null float64
TPP_Type                                 30312 non-null object
TPP_Start                                30312 non-null object
TPP_End                                  30312 non-null object
Product_Units_Per_Case                   30312 non-null float64
Product_CPG_COGS_Price                   30312 non-null float64
SIZE                                     30312 non-null object
dtypes: float64(7), object(15)
memory usage: 5.3+ MB

In [10]:
#create a copy of the original data set
sale=df_price_elasticity

In [11]:
sale.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30312 entries, 355324 to 385635
Data columns (total 22 columns):
Promo_ID                                 30312 non-null object
Promo_Name                               30312 non-null object
Retailer_Name                            30312 non-null object
Retailer_Store_ID                        30312 non-null object
Product_Category                         30312 non-null object
Product_Sub_Category                     30312 non-null object
Product_Unit_UPC                         30312 non-null object
Product_Group_ID                         30312 non-null object
Product_Brand                            30312 non-null object
Product_Brand_Category_Desc              30312 non-null object
Product_Unit_Description                 30312 non-null object
Retailer_Product_Base_Day_Unit_Volume    30312 non-null float64
TPP_Unit_Sale_Price                      30312 non-null float64
Retailer_Product_Regular_Unit_Price      30312 non-null float64
TPP_Incremental_Cases                    30312 non-null float64
TPP_Baseline_Cases_Volume                30312 non-null float64
TPP_Type                                 30312 non-null object
TPP_Start                                30312 non-null object
TPP_End                                  30312 non-null object
Product_Units_Per_Case                   30312 non-null float64
Product_CPG_COGS_Price                   30312 non-null float64
SIZE                                     30312 non-null object
dtypes: float64(7), object(15)
memory usage: 5.3+ MB

In [12]:
# create rename the sale price to price, create the cases and units field, drop fields you don't need anymore
#label all of the records as sale records

sale=sale.rename(index=str, columns={"TPP_Unit_Sale_Price": "PRICE"})
sale['CASES'] = sale['TPP_Baseline_Cases_Volume'] + sale['TPP_Incremental_Cases'] 
sale['GROUP']='ONSALE'
sale['UNITS']=sale['CASES']*sale['Product_Units_Per_Case']
sale=sale.drop(['TPP_Baseline_Cases_Volume', 'TPP_Incremental_Cases','Retailer_Product_Regular_Unit_Price','Retailer_Product_Base_Day_Unit_Volume'], axis=1)

In [13]:
sale.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30312 entries, 355324 to 385635
Data columns (total 21 columns):
Promo_ID                       30312 non-null object
Promo_Name                     30312 non-null object
Retailer_Name                  30312 non-null object
Retailer_Store_ID              30312 non-null object
Product_Category               30312 non-null object
Product_Sub_Category           30312 non-null object
Product_Unit_UPC               30312 non-null object
Product_Group_ID               30312 non-null object
Product_Brand                  30312 non-null object
Product_Brand_Category_Desc    30312 non-null object
Product_Unit_Description       30312 non-null object
PRICE                          30312 non-null float64
TPP_Type                       30312 non-null object
TPP_Start                      30312 non-null object
TPP_End                        30312 non-null object
Product_Units_Per_Case         30312 non-null float64
Product_CPG_COGS_Price         30312 non-null float64
SIZE                           30312 non-null object
CASES                          30312 non-null float64
GROUP                          30312 non-null object
UNITS                          30312 non-null float64
dtypes: float64(5), object(16)
memory usage: 5.1+ MB

In [14]:
#copy the orginal data set, create the non-sale prices
nosale=df_price_elasticity

In [15]:
nosale.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30312 entries, 355324 to 385635
Data columns (total 22 columns):
Promo_ID                                 30312 non-null object
Promo_Name                               30312 non-null object
Retailer_Name                            30312 non-null object
Retailer_Store_ID                        30312 non-null object
Product_Category                         30312 non-null object
Product_Sub_Category                     30312 non-null object
Product_Unit_UPC                         30312 non-null object
Product_Group_ID                         30312 non-null object
Product_Brand                            30312 non-null object
Product_Brand_Category_Desc              30312 non-null object
Product_Unit_Description                 30312 non-null object
Retailer_Product_Base_Day_Unit_Volume    30312 non-null float64
TPP_Unit_Sale_Price                      30312 non-null float64
Retailer_Product_Regular_Unit_Price      30312 non-null float64
TPP_Incremental_Cases                    30312 non-null float64
TPP_Baseline_Cases_Volume                30312 non-null float64
TPP_Type                                 30312 non-null object
TPP_Start                                30312 non-null object
TPP_End                                  30312 non-null object
Product_Units_Per_Case                   30312 non-null float64
Product_CPG_COGS_Price                   30312 non-null float64
SIZE                                     30312 non-null object
dtypes: float64(7), object(15)
memory usage: 5.3+ MB

In [16]:
#create the cases and price field
nosale=nosale.rename(index=str, columns={"TPP_Baseline_Cases_Volume": "CASES", "Retailer_Product_Regular_Unit_Price":"PRICE"})

In [17]:
nosale.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30312 entries, 355324 to 385635
Data columns (total 22 columns):
Promo_ID                                 30312 non-null object
Promo_Name                               30312 non-null object
Retailer_Name                            30312 non-null object
Retailer_Store_ID                        30312 non-null object
Product_Category                         30312 non-null object
Product_Sub_Category                     30312 non-null object
Product_Unit_UPC                         30312 non-null object
Product_Group_ID                         30312 non-null object
Product_Brand                            30312 non-null object
Product_Brand_Category_Desc              30312 non-null object
Product_Unit_Description                 30312 non-null object
Retailer_Product_Base_Day_Unit_Volume    30312 non-null float64
TPP_Unit_Sale_Price                      30312 non-null float64
PRICE                                    30312 non-null float64
TPP_Incremental_Cases                    30312 non-null float64
CASES                                    30312 non-null float64
TPP_Type                                 30312 non-null object
TPP_Start                                30312 non-null object
TPP_End                                  30312 non-null object
Product_Units_Per_Case                   30312 non-null float64
Product_CPG_COGS_Price                   30312 non-null float64
SIZE                                     30312 non-null object
dtypes: float64(7), object(15)
memory usage: 5.3+ MB

In [18]:
#Calculate the number of Units
nosale['UNITS']=nosale['CASES']*nosale['Product_Units_Per_Case']

In [19]:
#identify the prices as non-sale prices.
nosale['GROUP']='NOTONSALE'


#Remove stuff you don't need


nosale=nosale.drop([ 'TPP_Incremental_Cases','TPP_Unit_Sale_Price','Retailer_Product_Base_Day_Unit_Volume','TPP_Type'], axis=1)
nosale['TPP_Type']='N'

In [20]:
nosale.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Category,Product_Sub_Category,Product_Unit_UPC,Product_Group_ID,Product_Brand,Product_Brand_Category_Desc,...,PRICE,CASES,TPP_Start,TPP_End,Product_Units_Per_Case,Product_CPG_COGS_Price,SIZE,UNITS,GROUP,TPP_Type
355324,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,Household,Cleaners,33404-10164,D-H-C-L-64,Dottie's,Dottie's Cleaners Laundry 64 oz,...,3.92,2.0,2018-01-17,2018-01-26,8.0,2.78,64,16.0,NOTONSALE,N
355325,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,Household,Cleaners,33404-19921,D-H-C-L-121,Dottie's,Dottie's Cleaners Laundry 121 oz,...,7.36,3.0,2018-01-17,2018-01-26,3.0,5.21,21,9.0,NOTONSALE,N
355326,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,Household,Cleaners,33409-10100,D-H-C-AP-100,Dottie's,Dottie's Cleaners All Purpose 100 oz,...,6.76,1.0,2018-01-17,2018-01-26,12.0,4.79,00,12.0,NOTONSALE,N
355327,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,Household,Cleaners,33419-11051,D-H-C-L-51,Dottie's,Dottie's Cleaners Laundry 51 oz,...,9.11,1.0,2018-01-17,2018-01-26,18.0,6.45,51,18.0,NOTONSALE,N
355328,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,Household,Cleaners,33419-10129,D-H-C-L-129,Dottie's,Dottie's Cleaners Laundry 129 oz,...,13.14,1.0,2018-01-17,2018-01-26,12.0,9.31,29,12.0,NOTONSALE,N

In [21]:
sale.info()
nosale.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30312 entries, 355324 to 385635
Data columns (total 21 columns):
Promo_ID                       30312 non-null object
Promo_Name                     30312 non-null object
Retailer_Name                  30312 non-null object
Retailer_Store_ID              30312 non-null object
Product_Category               30312 non-null object
Product_Sub_Category           30312 non-null object
Product_Unit_UPC               30312 non-null object
Product_Group_ID               30312 non-null object
Product_Brand                  30312 non-null object
Product_Brand_Category_Desc    30312 non-null object
Product_Unit_Description       30312 non-null object
PRICE                          30312 non-null float64
TPP_Type                       30312 non-null object
TPP_Start                      30312 non-null object
TPP_End                        30312 non-null object
Product_Units_Per_Case         30312 non-null float64
Product_CPG_COGS_Price         30312 non-null float64
SIZE                           30312 non-null object
CASES                          30312 non-null float64
GROUP                          30312 non-null object
UNITS                          30312 non-null float64
dtypes: float64(5), object(16)
memory usage: 5.1+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 30312 entries, 355324 to 385635
Data columns (total 21 columns):
Promo_ID                       30312 non-null object
Promo_Name                     30312 non-null object
Retailer_Name                  30312 non-null object
Retailer_Store_ID              30312 non-null object
Product_Category               30312 non-null object
Product_Sub_Category           30312 non-null object
Product_Unit_UPC               30312 non-null object
Product_Group_ID               30312 non-null object
Product_Brand                  30312 non-null object
Product_Brand_Category_Desc    30312 non-null object
Product_Unit_Description       30312 non-null object
PRICE                          30312 non-null float64
CASES                          30312 non-null float64
TPP_Start                      30312 non-null object
TPP_End                        30312 non-null object
Product_Units_Per_Case         30312 non-null float64
Product_CPG_COGS_Price         30312 non-null float64
SIZE                           30312 non-null object
UNITS                          30312 non-null float64
GROUP                          30312 non-null object
TPP_Type                       30312 non-null object
dtypes: float64(5), object(16)
memory usage: 5.1+ MB

In [22]:
#include needed fields
nosale = nosale[['Promo_ID',
 'Promo_Name',
 'Retailer_Name',
 'Retailer_Store_ID',
 'Product_Group_ID',
 'Product_Unit_UPC',
 'Product_Brand',
 'Product_Brand_Category_Desc',
 'Product_Unit_Description',
 'PRICE',
 'TPP_Type',
 'TPP_Start',
 'TPP_End',
 'Product_Units_Per_Case',
 'Product_CPG_COGS_Price',
 'SIZE',
 'CASES',
 'GROUP',
 'UNITS']]

In [23]:
#include needed fields
sale = sale[['Promo_ID',
 'Promo_Name',
 'Retailer_Name',
 'Retailer_Store_ID',
 'Product_Group_ID',
 'Product_Unit_UPC',
 'Product_Brand',
 'Product_Brand_Category_Desc',
 'Product_Unit_Description',
 'PRICE',
 'TPP_Type',
 'TPP_Start',
 'TPP_End',
 'Product_Units_Per_Case',
 'Product_CPG_COGS_Price',
 'SIZE',
 'CASES',
 'GROUP',
 'UNITS']]

In [24]:
sale.info()
nosale.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30312 entries, 355324 to 385635
Data columns (total 19 columns):
Promo_ID                       30312 non-null object
Promo_Name                     30312 non-null object
Retailer_Name                  30312 non-null object
Retailer_Store_ID              30312 non-null object
Product_Group_ID               30312 non-null object
Product_Unit_UPC               30312 non-null object
Product_Brand                  30312 non-null object
Product_Brand_Category_Desc    30312 non-null object
Product_Unit_Description       30312 non-null object
PRICE                          30312 non-null float64
TPP_Type                       30312 non-null object
TPP_Start                      30312 non-null object
TPP_End                        30312 non-null object
Product_Units_Per_Case         30312 non-null float64
Product_CPG_COGS_Price         30312 non-null float64
SIZE                           30312 non-null object
CASES                          30312 non-null float64
GROUP                          30312 non-null object
UNITS                          30312 non-null float64
dtypes: float64(5), object(14)
memory usage: 4.6+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 30312 entries, 355324 to 385635
Data columns (total 19 columns):
Promo_ID                       30312 non-null object
Promo_Name                     30312 non-null object
Retailer_Name                  30312 non-null object
Retailer_Store_ID              30312 non-null object
Product_Group_ID               30312 non-null object
Product_Unit_UPC               30312 non-null object
Product_Brand                  30312 non-null object
Product_Brand_Category_Desc    30312 non-null object
Product_Unit_Description       30312 non-null object
PRICE                          30312 non-null float64
TPP_Type                       30312 non-null object
TPP_Start                      30312 non-null object
TPP_End                        30312 non-null object
Product_Units_Per_Case         30312 non-null float64
Product_CPG_COGS_Price         30312 non-null float64
SIZE                           30312 non-null object
CASES                          30312 non-null float64
GROUP                          30312 non-null object
UNITS                          30312 non-null float64
dtypes: float64(5), object(14)
memory usage: 4.6+ MB

In [25]:
#append the sale and non-sale records into one dataframe
df_total=pd.DataFrame(sale.append(nosale, ignore_index=True, verify_integrity=False))

In [26]:
#convert the tpp_start which is character to a pandas date field
df_total['date'] = pd.to_datetime(df_total['TPP_Start'])
df_total.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,TPP_Type,TPP_Start,TPP_End,Product_Units_Per_Case,Product_CPG_COGS_Price,SIZE,CASES,GROUP,UNITS,date
0,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,TPR,2018-01-17,2018-01-26,8.0,2.78,64,3.0,ONSALE,24.0,2018-01-17
1,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-121,33404-19921,Dottie's,Dottie's Cleaners Laundry 121 oz,Dottie's Bleach 121 oz,6.88,TPR,2018-01-17,2018-01-26,3.0,5.21,21,5.0,ONSALE,15.0,2018-01-17
2,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-AP-100,33409-10100,Dottie's,Dottie's Cleaners All Purpose 100 oz,Dottie's Multi-Surface Cleaner 100 oz,6.32,TPR,2018-01-17,2018-01-26,12.0,4.79,00,2.0,ONSALE,24.0,2018-01-17
3,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-51,33419-11051,Dottie's,Dottie's Cleaners Laundry 51 oz,Dottie's Fabric Softener 51 oz,8.51,TPR,2018-01-17,2018-01-26,18.0,6.45,51,2.0,ONSALE,36.0,2018-01-17
4,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-129,33419-10129,Dottie's,Dottie's Cleaners Laundry 129 oz,Dottie's Fabric Softener 129 oz,12.28,TPR,2018-01-17,2018-01-26,12.0,9.31,29,2.0,ONSALE,24.0,2018-01-17

In [27]:
#create a field for year and month
df_total['year'], df_total['month'] = df_total['date'].dt.year, df_total['date'].dt.month
df_total.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,TPP_End,Product_Units_Per_Case,Product_CPG_COGS_Price,SIZE,CASES,GROUP,UNITS,date,year,month
0,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-26,8.0,2.78,64,3.0,ONSALE,24.0,2018-01-17,2018,1
1,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-121,33404-19921,Dottie's,Dottie's Cleaners Laundry 121 oz,Dottie's Bleach 121 oz,6.88,...,2018-01-26,3.0,5.21,21,5.0,ONSALE,15.0,2018-01-17,2018,1
2,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-AP-100,33409-10100,Dottie's,Dottie's Cleaners All Purpose 100 oz,Dottie's Multi-Surface Cleaner 100 oz,6.32,...,2018-01-26,12.0,4.79,00,2.0,ONSALE,24.0,2018-01-17,2018,1
3,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-51,33419-11051,Dottie's,Dottie's Cleaners Laundry 51 oz,Dottie's Fabric Softener 51 oz,8.51,...,2018-01-26,18.0,6.45,51,2.0,ONSALE,36.0,2018-01-17,2018,1
4,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-129,33419-10129,Dottie's,Dottie's Cleaners Laundry 129 oz,Dottie's Fabric Softener 129 oz,12.28,...,2018-01-26,12.0,9.31,29,2.0,ONSALE,24.0,2018-01-17,2018,1

In [28]:
#assign random numbers to each retailer
wookie = pd.DataFrame(df_total.groupby(['Retailer_Store_ID'])['PRICE'].mean())
wookie=wookie.drop(['PRICE'], axis=1)

In [29]:
wookie['Retailer_R'] = (np.random.randint(-30, 60, wookie.shape[0]))/1000
wookie.reset_index(level=0, inplace=True)
wookie.head()

  Retailer_Store_ID  Retailer_R
0   12345-10024-126       0.045
1   12345-14213-136      -0.002
2   12345-14601-157       0.044
3   12345-15225-129      -0.013
4   12345-15225-167       0.016

In [30]:
df_total1 =df_total.merge(wookie, on=['Retailer_Store_ID'], how='inner')
df_total1.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,Product_Units_Per_Case,Product_CPG_COGS_Price,SIZE,CASES,GROUP,UNITS,date,year,month,Retailer_R
0,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,8.0,2.78,64,3.0,ONSALE,24.0,2018-01-17,2018,1,-0.019
1,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-121,33404-19921,Dottie's,Dottie's Cleaners Laundry 121 oz,Dottie's Bleach 121 oz,6.88,...,3.0,5.21,21,5.0,ONSALE,15.0,2018-01-17,2018,1,-0.019
2,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-AP-100,33409-10100,Dottie's,Dottie's Cleaners All Purpose 100 oz,Dottie's Multi-Surface Cleaner 100 oz,6.32,...,12.0,4.79,00,2.0,ONSALE,24.0,2018-01-17,2018,1,-0.019
3,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-51,33419-11051,Dottie's,Dottie's Cleaners Laundry 51 oz,Dottie's Fabric Softener 51 oz,8.51,...,18.0,6.45,51,2.0,ONSALE,36.0,2018-01-17,2018,1,-0.019
4,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-129,33419-10129,Dottie's,Dottie's Cleaners Laundry 129 oz,Dottie's Fabric Softener 129 oz,12.28,...,12.0,9.31,29,2.0,ONSALE,24.0,2018-01-17,2018,1,-0.019

In [31]:
#assign random numbers to each product group id
df_total1.Product_Group_ID.value_counts(dropna = False).sort_index()

D-H-C-AP-10     3368
D-H-C-AP-100    3368
D-H-C-AP-128    3368
D-H-C-AP-20     3368
D-H-C-AP-23     3368
D-H-C-AP-64     3368
D-H-C-AP-7.5    6736
D-H-C-K-38      3368
D-H-C-K-4       3368
D-H-C-K-67      3368
D-H-C-K-75      3368
D-H-C-K-8       3368
D-H-C-L-121     3368
D-H-C-L-129     3368
D-H-C-L-51      3368
D-H-C-L-64      6736
Name: Product_Group_ID, dtype: int64

In [32]:
 wookie = pd.DataFrame(df_total1.groupby(['Product_Group_ID'])['PRICE'].mean())
wookie=wookie.drop(['PRICE'], axis=1)

In [33]:
wookie['PRODUCT_GROUP_ID_R'] = (np.random.randint(-30, 60, wookie.shape[0]))/1000
wookie.reset_index(level=0, inplace=True)
wookie.head()

  Product_Group_ID  PRODUCT_GROUP_ID_R
0     D-H-C-AP-10                0.026
1     D-H-C-AP-100              -0.012
2     D-H-C-AP-128               0.059
3      D-H-C-AP-20               0.057
4      D-H-C-AP-23               0.000

In [34]:
#!pip install plotly --upgrade

In [35]:
df_total2 =df_total1.merge(wookie, on=['Product_Group_ID'], how='inner')
df_total2.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,Product_CPG_COGS_Price,SIZE,CASES,GROUP,UNITS,date,year,month,Retailer_R,PRODUCT_GROUP_ID_R
0,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2.78,64,3.0,ONSALE,24.0,2018-01-17,2018,1,-0.019,-0.024
1,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33455-11795,Dottie's,Dottie's Cleaners Laundry 95 oz,Dottie's Laundry Detergent 95 oz,3.66,...,2.78,64,3.0,ONSALE,24.0,2018-01-17,2018,1,-0.019,-0.024
2,Brandega-43270,Mother Knows Best,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2.78,64,2.0,ONSALE,16.0,2019-12-25,2019,12,-0.019,-0.024
3,Brandega-43270,Mother Knows Best,Botann's,12345-94249-107,D-H-C-L-64,33455-11795,Dottie's,Dottie's Cleaners Laundry 95 oz,Dottie's Laundry Detergent 95 oz,3.66,...,2.78,64,2.0,ONSALE,16.0,2019-12-25,2019,12,-0.019,-0.024
4,Brandega-53999,Spring into Clean,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2.78,64,2.0,ONSALE,16.0,2019-03-04,2019,3,-0.019,-0.024

In [36]:
#assign random numbers to each product unit upc value
df_total2.Product_Unit_UPC.value_counts(dropna = False).sort_index()

33404-10164    3368
33404-19921    3368
33409-10100    3368
33419-10129    3368
33419-11051    3368
33421-11164    3368
33437-33304    3368
33437-33308    3368
33437-33367    3368
33455-11795    3368
33459-20023    3368
33472-10828    3368
33472-11038    3368
33472-11075    3368
33477-10128    3368
33477-11007    3368
33477-11020    3368
33488-14010    3368
Name: Product_Unit_UPC, dtype: int64

In [37]:
wookie = pd.DataFrame(df_total2.groupby(['Product_Unit_UPC'])['PRICE'].mean())
wookie=wookie.drop(['PRICE'], axis=1)

wookie['Product_Unit_UPC_R'] = (np.random.randint(-30, 60, wookie.shape[0]))/1000
wookie.reset_index(level=0, inplace=True)
wookie.head()
df_total3 =df_total2.merge(wookie, on=['Product_Unit_UPC'], how='inner')
df_total3.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,SIZE,CASES,GROUP,UNITS,date,year,month,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R
0,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,64,3.0,ONSALE,24.0,2018-01-17,2018,1,-0.019,-0.024,0.01
1,Brandega-43270,Mother Knows Best,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,64,2.0,ONSALE,16.0,2019-12-25,2019,12,-0.019,-0.024,0.01
2,Brandega-53999,Spring into Clean,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,64,2.0,ONSALE,16.0,2019-03-04,2019,3,-0.019,-0.024,0.01
3,Brandega-55680,Fresh Feeling,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,64,2.0,ONSALE,16.0,2019-09-13,2019,9,-0.019,-0.024,0.01
4,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,64,2.0,NOTONSALE,16.0,2018-01-17,2018,1,-0.019,-0.024,0.01

In [38]:
#assign random numbers to each promo
df_total2.Promo_Name.value_counts(dropna = False).sort_index()

Fresh Feeling        15156
Mother Knows Best    15156
Move to the Beat     15156
Spring into Clean    15156
Name: Promo_Name, dtype: int64

In [39]:
wookie = pd.DataFrame(df_total3.groupby(['Promo_Name'])['PRICE'].mean())
wookie=wookie.drop(['PRICE'], axis=1)

wookie['Promo_Name_R'] = (np.random.randint(-30, 60, wookie.shape[0]))/1000
wookie.reset_index(level=0, inplace=True)
wookie.head()
df_total4 =df_total3.merge(wookie, on=['Promo_Name'], how='inner')
df_total4.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,CASES,GROUP,UNITS,date,year,month,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R
0,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,3.0,ONSALE,24.0,2018-01-17,2018,1,-0.019,-0.024,0.01,-0.021
1,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2.0,NOTONSALE,16.0,2018-01-17,2018,1,-0.019,-0.024,0.01,-0.021
2,Brandega-18907,Move to the Beat,Botann's,12345-79914-108,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,3.0,ONSALE,24.0,2018-01-17,2018,1,0.005,-0.024,0.01,-0.021
3,Brandega-18907,Move to the Beat,Botann's,12345-79914-108,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2.0,NOTONSALE,16.0,2018-01-17,2018,1,0.005,-0.024,0.01,-0.021
4,Brandega-18907,Move to the Beat,Botann's,12345-90005-109,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,3.0,ONSALE,24.0,2018-01-17,2018,1,-0.010,-0.024,0.01,-0.021

In [40]:
#assign different values to sale and non-sale records
df_total4['GROUP_R'] = np.where(df_total4['GROUP'] == 'ONSALE', -0.10, 0.01)
df_total4.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,GROUP,UNITS,date,year,month,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R,GROUP_R
0,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,ONSALE,24.0,2018-01-17,2018,1,-0.019,-0.024,0.01,-0.021,-0.10
1,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,NOTONSALE,16.0,2018-01-17,2018,1,-0.019,-0.024,0.01,-0.021,0.01
2,Brandega-18907,Move to the Beat,Botann's,12345-79914-108,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,ONSALE,24.0,2018-01-17,2018,1,0.005,-0.024,0.01,-0.021,-0.10
3,Brandega-18907,Move to the Beat,Botann's,12345-79914-108,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,NOTONSALE,16.0,2018-01-17,2018,1,0.005,-0.024,0.01,-0.021,0.01
4,Brandega-18907,Move to the Beat,Botann's,12345-90005-109,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,ONSALE,24.0,2018-01-17,2018,1,-0.010,-0.024,0.01,-0.021,-0.10

In [41]:
df_total4.month.value_counts(dropna = False).sort_index()

1     15156
3     15156
9     15156
12    15156
Name: month, dtype: int64

In [42]:
#assign values to each month
conditions = [
    (df_total4['month'] == 2),
    (df_total4['month'] ==4),
    (df_total4['month'] ==7)]
choices = [-0.03, 0.02, 0.06]
df_total4['month_R'] = np.select(conditions, choices, default=0.02)

In [43]:
df_total4.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,UNITS,date,year,month,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R,GROUP_R,month_R
0,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,24.0,2018-01-17,2018,1,-0.019,-0.024,0.01,-0.021,-0.10,0.02
1,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,16.0,2018-01-17,2018,1,-0.019,-0.024,0.01,-0.021,0.01,0.02
2,Brandega-18907,Move to the Beat,Botann's,12345-79914-108,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,24.0,2018-01-17,2018,1,0.005,-0.024,0.01,-0.021,-0.10,0.02
3,Brandega-18907,Move to the Beat,Botann's,12345-79914-108,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,16.0,2018-01-17,2018,1,0.005,-0.024,0.01,-0.021,0.01,0.02
4,Brandega-18907,Move to the Beat,Botann's,12345-90005-109,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,24.0,2018-01-17,2018,1,-0.010,-0.024,0.01,-0.021,-0.10,0.02

In [44]:
#generate a random number for each row that is either 1 or -1
import random
df_total4['randNumCol'] = np.random.choice([1, -1], df_total4.shape[0])
df_total4.head(100)

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,date,year,month,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R,GROUP_R,month_R,randNumCol
0,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,-0.019,-0.024,0.01,-0.021,-0.10,0.02,-1
1,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,-0.019,-0.024,0.01,-0.021,0.01,0.02,1
2,Brandega-18907,Move to the Beat,Botann's,12345-79914-108,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.005,-0.024,0.01,-0.021,-0.10,0.02,1
3,Brandega-18907,Move to the Beat,Botann's,12345-79914-108,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.005,-0.024,0.01,-0.021,0.01,0.02,1
4,Brandega-18907,Move to the Beat,Botann's,12345-90005-109,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,-0.010,-0.024,0.01,-0.021,-0.10,0.02,-1
5,Brandega-18907,Move to the Beat,Botann's,12345-90005-109,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,-0.010,-0.024,0.01,-0.021,0.01,0.02,1
6,Brandega-18907,Move to the Beat,Botann's,12345-33233-110,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.005,-0.024,0.01,-0.021,-0.10,0.02,-1
7,Brandega-18907,Move to the Beat,Botann's,12345-33233-110,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.005,-0.024,0.01,-0.021,0.01,0.02,-1
8,Brandega-18907,Move to the Beat,Botann's,12345-28816-111,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.046,-0.024,0.01,-0.021,-0.10,0.02,1
9,Brandega-18907,Move to the Beat,Botann's,12345-28816-111,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.046,-0.024,0.01,-0.021,0.01,0.02,1
10,Brandega-18907,Move to the Beat,Botann's,12345-80524-112,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.039,-0.024,0.01,-0.021,-0.10,0.02,-1
11,Brandega-18907,Move to the Beat,Botann's,12345-80524-112,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.039,-0.024,0.01,-0.021,0.01,0.02,-1
12,Brandega-18907,Move to the Beat,Botann's,12345-78766-113,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,-0.005,-0.024,0.01,-0.021,-0.10,0.02,1
13,Brandega-18907,Move to the Beat,Botann's,12345-78766-113,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,-0.005,-0.024,0.01,-0.021,0.01,0.02,1
14,Brandega-18907,Move to the Beat,Botann's,12345-78224-114,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,-0.005,-0.024,0.01,-0.021,-0.10,0.02,-1
15,Brandega-18907,Move to the Beat,Botann's,12345-78224-114,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,-0.005,-0.024,0.01,-0.021,0.01,0.02,-1
16,Brandega-18907,Move to the Beat,Botann's,12345-92102-115,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.043,-0.024,0.01,-0.021,-0.10,0.02,-1
17,Brandega-18907,Move to the Beat,Botann's,12345-92102-115,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.043,-0.024,0.01,-0.021,0.01,0.02,1
18,Brandega-18907,Move to the Beat,Botann's,12345-90005-116,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,-0.021,-0.024,0.01,-0.021,-0.10,0.02,1
19,Brandega-18907,Move to the Beat,Botann's,12345-90005-116,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,-0.021,-0.024,0.01,-0.021,0.01,0.02,1
20,Brandega-18907,Move to the Beat,Botann's,12345-28816-117,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,-0.022,-0.024,0.01,-0.021,-0.10,0.02,1
21,Brandega-18907,Move to the Beat,Botann's,12345-28816-117,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,-0.022,-0.024,0.01,-0.021,0.01,0.02,1
22,Brandega-18907,Move to the Beat,Botann's,12345-22336-118,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,-0.022,-0.024,0.01,-0.021,-0.10,0.02,-1
23,Brandega-18907,Move to the Beat,Botann's,12345-22336-118,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,-0.022,-0.024,0.01,-0.021,0.01,0.02,-1
24,Brandega-18907,Move to the Beat,Botann's,12345-75240-119,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.052,-0.024,0.01,-0.021,-0.10,0.02,1
25,Brandega-18907,Move to the Beat,Botann's,12345-75240-119,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.052,-0.024,0.01,-0.021,0.01,0.02,-1
26,Brandega-18907,Move to the Beat,Botann's,12345-90005-120,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.033,-0.024,0.01,-0.021,-0.10,0.02,-1
27,Brandega-18907,Move to the Beat,Botann's,12345-90005-120,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.033,-0.024,0.01,-0.021,0.01,0.02,-1
28,Brandega-18907,Move to the Beat,Botann's,12345-78224-121,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,-0.011,-0.024,0.01,-0.021,-0.10,0.02,1
29,Brandega-18907,Move to the Beat,Botann's,12345-78224-121,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,-0.011,-0.024,0.01,-0.021,0.01,0.02,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,Brandega-18907,Move to the Beat,Botann's,12345-73502-142,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.042,-0.024,0.01,-0.021,-0.10,0.02,1
71,Brandega-18907,Move to the Beat,Botann's,12345-73502-142,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.042,-0.024,0.01,-0.021,0.01,0.02,1
72,Brandega-18907,Move to the Beat,Botann's,12345-32277-143,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,-0.023,-0.024,0.01,-0.021,-0.10,0.02,-1
73,Brandega-18907,Move to the Beat,Botann's,12345-32277-143,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,-0.023,-0.024,0.01,-0.021,0.01,0.02,1
74,Brandega-18907,Move to the Beat,Botann's,12345-65616-144,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.021,-0.024,0.01,-0.021,-0.10,0.02,1
75,Brandega-18907,Move to the Beat,Botann's,12345-65616-144,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.021,-0.024,0.01,-0.021,0.01,0.02,-1
76,Brandega-18907,Move to the Beat,Botann's,12345-26003-145,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,-0.012,-0.024,0.01,-0.021,-0.10,0.02,-1
77,Brandega-18907,Move to the Beat,Botann's,12345-26003-145,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,-0.012,-0.024,0.01,-0.021,0.01,0.02,-1
78,Brandega-18907,Move to the Beat,Botann's,12345-22336-146,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.003,-0.024,0.01,-0.021,-0.10,0.02,1
79,Brandega-18907,Move to the Beat,Botann's,12345-22336-146,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.003,-0.024,0.01,-0.021,0.01,0.02,-1
80,Brandega-18907,Move to the Beat,Botann's,12345-32550-147,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.009,-0.024,0.01,-0.021,-0.10,0.02,1
81,Brandega-18907,Move to the Beat,Botann's,12345-32550-147,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.009,-0.024,0.01,-0.021,0.01,0.02,-1
82,Brandega-18907,Move to the Beat,Botann's,12345-78224-148,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.012,-0.024,0.01,-0.021,-0.10,0.02,1
83,Brandega-18907,Move to the Beat,Botann's,12345-78224-148,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.012,-0.024,0.01,-0.021,0.01,0.02,1
84,Brandega-18907,Move to the Beat,Botann's,12345-94104-149,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,-0.019,-0.024,0.01,-0.021,-0.10,0.02,1
85,Brandega-18907,Move to the Beat,Botann's,12345-94104-149,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,-0.019,-0.024,0.01,-0.021,0.01,0.02,1
86,Brandega-18907,Move to the Beat,Botann's,12345-94249-150,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.018,-0.024,0.01,-0.021,-0.10,0.02,1
87,Brandega-18907,Move to the Beat,Botann's,12345-94249-150,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.018,-0.024,0.01,-0.021,0.01,0.02,-1
88,Brandega-18907,Move to the Beat,Botann's,12345-85261-151,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.026,-0.024,0.01,-0.021,-0.10,0.02,1
89,Brandega-18907,Move to the Beat,Botann's,12345-85261-151,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.026,-0.024,0.01,-0.021,0.01,0.02,-1
90,Brandega-18907,Move to the Beat,Botann's,12345-37421-152,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.041,-0.024,0.01,-0.021,-0.10,0.02,1
91,Brandega-18907,Move to the Beat,Botann's,12345-37421-152,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.041,-0.024,0.01,-0.021,0.01,0.02,1
92,Brandega-18907,Move to the Beat,Botann's,12345-53284-153,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.006,-0.024,0.01,-0.021,-0.10,0.02,1
93,Brandega-18907,Move to the Beat,Botann's,12345-53284-153,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.006,-0.024,0.01,-0.021,0.01,0.02,1
94,Brandega-18907,Move to the Beat,Botann's,12345-79914-154,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,0.011,-0.024,0.01,-0.021,-0.10,0.02,1
95,Brandega-18907,Move to the Beat,Botann's,12345-79914-154,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,0.011,-0.024,0.01,-0.021,0.01,0.02,-1
96,Brandega-18907,Move to the Beat,Botann's,12345-65110-155,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,-0.027,-0.024,0.01,-0.021,-0.10,0.02,-1
97,Brandega-18907,Move to the Beat,Botann's,12345-65110-155,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,-0.027,-0.024,0.01,-0.021,0.01,0.02,-1
98,Brandega-18907,Move to the Beat,Botann's,12345-48206-156,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018-01-17,2018,1,-0.026,-0.024,0.01,-0.021,-0.10,0.02,1
99,Brandega-18907,Move to the Beat,Botann's,12345-48206-156,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018-01-17,2018,1,-0.026,-0.024,0.01,-0.021,0.01,0.02,-1

In [45]:
#sum the generated numbers for each row, making a unique value for each row called total_r

cols = ['Retailer_R','PRODUCT_GROUP_ID_R','Product_Unit_UPC_R','Promo_Name_R','GROUP_R','month_R']
df_total4['TOTAL_R'] = df_total4[cols].astype(float).sum(axis=1)

In [46]:
df_total4.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,year,month,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R,GROUP_R,month_R,randNumCol,TOTAL_R
0,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018,1,-0.019,-0.024,0.01,-0.021,-0.10,0.02,-1,-1.340000e-01
1,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018,1,-0.019,-0.024,0.01,-0.021,0.01,0.02,1,-2.400000e-02
2,Brandega-18907,Move to the Beat,Botann's,12345-79914-108,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018,1,0.005,-0.024,0.01,-0.021,-0.10,0.02,1,-1.100000e-01
3,Brandega-18907,Move to the Beat,Botann's,12345-79914-108,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,2018,1,0.005,-0.024,0.01,-0.021,0.01,0.02,1,3.469447e-18
4,Brandega-18907,Move to the Beat,Botann's,12345-90005-109,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,2018,1,-0.010,-0.024,0.01,-0.021,-0.10,0.02,-1,-1.250000e-01

In [47]:
df_total4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60624 entries, 0 to 60623
Data columns (total 30 columns):
Promo_ID                       60624 non-null object
Promo_Name                     60624 non-null object
Retailer_Name                  60624 non-null object
Retailer_Store_ID              60624 non-null object
Product_Group_ID               60624 non-null object
Product_Unit_UPC               60624 non-null object
Product_Brand                  60624 non-null object
Product_Brand_Category_Desc    60624 non-null object
Product_Unit_Description       60624 non-null object
PRICE                          60624 non-null float64
TPP_Type                       60624 non-null object
TPP_Start                      60624 non-null object
TPP_End                        60624 non-null object
Product_Units_Per_Case         60624 non-null float64
Product_CPG_COGS_Price         60624 non-null float64
SIZE                           60624 non-null object
CASES                          60624 non-null float64
GROUP                          60624 non-null object
UNITS                          60624 non-null float64
date                           60624 non-null datetime64[ns]
year                           60624 non-null int64
month                          60624 non-null int64
Retailer_R                     60624 non-null float64
PRODUCT_GROUP_ID_R             60624 non-null float64
Product_Unit_UPC_R             60624 non-null float64
Promo_Name_R                   60624 non-null float64
GROUP_R                        60624 non-null float64
month_R                        60624 non-null float64
randNumCol                     60624 non-null int64
TOTAL_R                        60624 non-null float64
dtypes: datetime64[ns](1), float64(12), int64(3), object(14)
memory usage: 14.3+ MB

In [48]:
#create new prices based on the adjustment numbers generated on the previous lines
df_total4['PRICE_R']=df_total4['PRICE']*(1.0-(df_total4['randNumCol']*df_total4['TOTAL_R']))
df_total4['UNITS_R']=df_total4['UNITS']*(1.0+(df_total4['randNumCol']*df_total4['TOTAL_R']))

In [49]:
df_total4.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R,GROUP_R,month_R,randNumCol,TOTAL_R,PRICE_R,UNITS_R
0,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,-0.019,-0.024,0.01,-0.021,-0.10,0.02,-1,-1.340000e-01,3.16956,27.216
1,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,-0.019,-0.024,0.01,-0.021,0.01,0.02,1,-2.400000e-02,4.01408,15.616
2,Brandega-18907,Move to the Beat,Botann's,12345-79914-108,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,0.005,-0.024,0.01,-0.021,-0.10,0.02,1,-1.100000e-01,4.06260,21.360
3,Brandega-18907,Move to the Beat,Botann's,12345-79914-108,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,0.005,-0.024,0.01,-0.021,0.01,0.02,1,3.469447e-18,3.92000,16.000
4,Brandega-18907,Move to the Beat,Botann's,12345-90005-109,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,-0.010,-0.024,0.01,-0.021,-0.10,0.02,-1,-1.250000e-01,3.20250,27.000

In [50]:
#Make sure that size is always positive, create a new variable called price_size convert size to a numeric value
df_total4.SIZE = df_total4.SIZE.astype(float).fillna(0.0)


df_total4['PRICE_SIZE']=df_total4['PRICE_R']*df_total4['SIZE']


df_total4.SIZE.value_counts(dropna = False).sort_index()

-8.0      3368
-4.0      3368
 0.0      6736
 0.5      6736
 20.0     3368
 21.0     3368
 23.0     3368
 28.0     3368
 29.0     3368
 38.0     3368
 51.0     3368
 64.0    10104
 67.0     3368
 75.0     3368
Name: SIZE, dtype: int64

In [51]:
#create a dummy variable for ice cream
df_total4['SIZE_16'] = np.where(df_total4['SIZE'] == 16, 1, 0)
df_total4['SIZE_16_PRICE']=df_total4['SIZE_16']*df_total4['PRICE']
df_total4.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,Promo_Name_R,GROUP_R,month_R,randNumCol,TOTAL_R,PRICE_R,UNITS_R,PRICE_SIZE,SIZE_16,SIZE_16_PRICE
0,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,-0.021,-0.10,0.02,-1,-1.340000e-01,3.16956,27.216,202.85184,0,0.0
1,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,-0.021,0.01,0.02,1,-2.400000e-02,4.01408,15.616,256.90112,0,0.0
2,Brandega-18907,Move to the Beat,Botann's,12345-79914-108,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,-0.021,-0.10,0.02,1,-1.100000e-01,4.06260,21.360,260.00640,0,0.0
3,Brandega-18907,Move to the Beat,Botann's,12345-79914-108,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.92,...,-0.021,0.01,0.02,1,3.469447e-18,3.92000,16.000,250.88000,0,0.0
4,Brandega-18907,Move to the Beat,Botann's,12345-90005-109,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,3.66,...,-0.021,-0.10,0.02,-1,-1.250000e-01,3.20250,27.000,204.96000,0,0.0

In [52]:
#bring in the stats library to build the model
import statsmodels.api as sm  
#scikit learn is another library that you could use.  Its focus is more on prediction.  This library is more focused on understanding why and how certain variables impact your target.  Which is quantity in this case

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [53]:
df_total4=df_total4.drop(['PRICE'], axis=1)

In [54]:
#make up multiple price points per campaign

v = df_total4[['PRICE_R','TOTAL_R','SIZE','PRICE_SIZE','UNITS_R']]
w = df_total4[['PRICE_R','TOTAL_R','SIZE','PRICE_SIZE','UNITS_R']]
x = df_total4[['PRICE_R','TOTAL_R','SIZE','PRICE_SIZE','UNITS_R']]
y = df_total4[['PRICE_R','TOTAL_R','SIZE','PRICE_SIZE','UNITS_R']]
z = df_total4[['PRICE_R','TOTAL_R','SIZE','PRICE_SIZE','UNITS_R']]

In [55]:
pricev = pd.DataFrame((v['PRICE_R']*0.95))
pricew = pd.DataFrame((w['PRICE_R']*0.85))
pricey = pd.DataFrame((y['PRICE_R']*0.90))
pricez= pd.DataFrame((z['PRICE_R']*0.80))

qv = pd.DataFrame((v['UNITS_R']*1.05))
qw = pd.DataFrame((w['UNITS_R']*1.15))
qy = pd.DataFrame((y['UNITS_R']*1.10))
qz= pd.DataFrame((z['UNITS_R']*1.20))

In [56]:
df_total4.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,TPP_Type,...,Promo_Name_R,GROUP_R,month_R,randNumCol,TOTAL_R,PRICE_R,UNITS_R,PRICE_SIZE,SIZE_16,SIZE_16_PRICE
0,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,TPR,...,-0.021,-0.10,0.02,-1,-1.340000e-01,3.16956,27.216,202.85184,0,0.0
1,Brandega-18907,Move to the Beat,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,N,...,-0.021,0.01,0.02,1,-2.400000e-02,4.01408,15.616,256.90112,0,0.0
2,Brandega-18907,Move to the Beat,Botann's,12345-79914-108,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,TPR,...,-0.021,-0.10,0.02,1,-1.100000e-01,4.06260,21.360,260.00640,0,0.0
3,Brandega-18907,Move to the Beat,Botann's,12345-79914-108,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,N,...,-0.021,0.01,0.02,1,3.469447e-18,3.92000,16.000,250.88000,0,0.0
4,Brandega-18907,Move to the Beat,Botann's,12345-90005-109,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,TPR,...,-0.021,-0.10,0.02,-1,-1.250000e-01,3.20250,27.000,204.96000,0,0.0

In [57]:
v=v.drop(['PRICE_R','UNITS_R'], axis=1)
v = pd.concat([v, pricev,qv], axis=1)
v['PRICE_POINT']='V'
stuff=df_total4[['Promo_ID','Retailer_Store_ID','Product_Unit_UPC','TPP_Type']]
v = pd.concat([v, stuff], axis=1)

In [58]:

w=w.drop(['PRICE_R','UNITS_R'], axis=1)
w = pd.concat([w, pricew,qw], axis=1)
w['PRICE_POINT']='W'

w = pd.concat([w, stuff], axis=1)

y=y.drop(['PRICE_R','UNITS_R'], axis=1)
y = pd.concat([y, pricey,qy], axis=1)
y['PRICE_POINT']='Y'
y = pd.concat([y, stuff], axis=1)

z=z.drop(['PRICE_R','UNITS_R'], axis=1)
z = pd.concat([z, pricez,qz], axis=1)
z['PRICE_POINT']='Z'
z = pd.concat([z, stuff], axis=1)

x['PRICE_POINT']='X'
x = pd.concat([x, stuff], axis=1)

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [59]:
xxx=pd.concat([v,w,x,y,z],axis=0)

In [60]:
#build the ols model

independent=xxx[['PRICE_R','TOTAL_R','SIZE','PRICE_SIZE']]
P=xxx['PRICE_POINT']
stuff=xxx[['Promo_ID','Retailer_Store_ID','Product_Unit_UPC','TPP_Type']]

independent = sm.add_constant(independent, prepend=False)

dependent=xxx['UNITS_R']

In [61]:
mod = sm.OLS(dependent, independent)

In [62]:
res = mod.fit()

In [63]:
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                UNITS_R   R-squared:                       0.460
Model:                            OLS   Adj. R-squared:                  0.460
Method:                 Least Squares   F-statistic:                 6.446e+04
Date:                Thu, 17 Jan 2019   Prob (F-statistic):               0.00
Time:                        17:44:05   Log-Likelihood:            -1.0494e+06
No. Observations:              303120   AIC:                         2.099e+06
Df Residuals:                  303115   BIC:                         2.099e+06
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
PRICE_R       -1.1220      0.007   -168.439      0.000      -1.135      -1.109
TOTAL_R      -76.3928      0.184   -414.235      0.000     -76.754     -76.031
SIZE          -0.1834      0.001   -176.305      0.000      -0.185      -0.181
PRICE_SIZE     0.0160      0.000    119.549      0.000       0.016       0.016
const         28.7984      0.036    804.937      0.000      28.728      28.869
==============================================================================
Omnibus:                    39848.600   Durbin-Watson:                   0.863
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            68774.948
Skew:                           0.884   Prob(JB):                         0.00
Kurtosis:                       4.523   Cond. No.                     5.47e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.47e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [64]:
ypred = pd.DataFrame(res.predict(independent))
ypred.columns = ['P_UNITS']

In [65]:
model_output=pd.concat([ypred,independent,stuff,P], axis=1)
model_output.head()

,P_UNITS,PRICE_R,TOTAL_R,SIZE,PRICE_SIZE,const,Promo_ID,Retailer_Store_ID,Product_Unit_UPC,TPP_Type,PRICE_POINT
0,27.165711,3.011082,-1.340000e-01,64.0,202.85184,1.0,Brandega-18907,12345-94249-107,33404-10164,TPR,V
1,18.726540,3.813376,-2.400000e-02,64.0,256.90112,1.0,Brandega-18907,12345-94249-107,33404-10164,N,V
2,25.294258,3.859470,-1.100000e-01,64.0,260.00640,1.0,Brandega-18907,12345-79914-108,33404-10164,TPR,V
3,16.897118,3.724000,3.469447e-18,64.0,250.88000,1.0,Brandega-18907,12345-79914-108,33404-10164,N,V
4,26.476773,3.042375,-1.250000e-01,64.0,204.96000,1.0,Brandega-18907,12345-90005-109,33404-10164,TPR,V

In [66]:
df_main_stuff=df_total4.drop(['PRICE_R','TOTAL_R','SIZE','PRICE_SIZE'], axis=1)
df_main_stuff.columns

Index(['Promo_ID', 'Promo_Name', 'Retailer_Name', 'Retailer_Store_ID',
       'Product_Group_ID', 'Product_Unit_UPC', 'Product_Brand',
       'Product_Brand_Category_Desc', 'Product_Unit_Description', 'TPP_Type',
       'TPP_Start', 'TPP_End', 'Product_Units_Per_Case',
       'Product_CPG_COGS_Price', 'CASES', 'GROUP', 'UNITS', 'date', 'year',
       'month', 'Retailer_R', 'PRODUCT_GROUP_ID_R', 'Product_Unit_UPC_R',
       'Promo_Name_R', 'GROUP_R', 'month_R', 'randNumCol', 'UNITS_R',
       'SIZE_16', 'SIZE_16_PRICE'],
      dtype='object')

In [67]:
df_main_stuff=df_main_stuff.drop_duplicates(subset=['Promo_ID','Retailer_Store_ID','Product_Unit_UPC','TPP_Type'], keep='first', inplace=False)
df_main_stuff.shape

(60624, 30)

In [68]:
df_total5 =model_output.merge(df_main_stuff, on=['Promo_ID','Retailer_Store_ID','Product_Unit_UPC','TPP_Type'], how='inner')
df_total5.shape

(303120, 37)

In [69]:
df_total5.describe()

,P_UNITS,PRICE_R,TOTAL_R,SIZE,PRICE_SIZE,const,Product_Units_Per_Case,Product_CPG_COGS_Price,CASES,UNITS,...,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R,GROUP_R,month_R,randNumCol,UNITS_R,SIZE_16,SIZE_16_PRICE
count,303120.000000,303120.000000,303120.000000,303120.000000,303120.000000,303120.0,303120.000000,303120.000000,303120.000000,303120.000000,...,303120.000000,303120.000000,303120.000000,303120.000000,303120.000,3.031200e+05,303120.000000,303120.000000,303120.0,303120.0
mean,18.872410,6.447082,0.021138,29.611111,272.157866,1.0,10.500000,5.247222,1.819444,17.145833,...,0.015333,0.010944,0.005611,0.014250,-0.045,2.000000e-02,0.001386,17.156737,0.0,0.0
std,7.113541,4.070035,0.076951,27.628310,311.490454,0.0,5.439065,3.231908,0.871246,9.336301,...,0.025138,0.032094,0.021407,0.036465,0.055,1.302675e-13,1.000001,9.455199,0.0,0.0
min,-4.868279,1.344288,-0.174000,-8.000000,-43.572800,1.0,3.000000,1.520000,1.000000,4.000000,...,-0.030000,-0.024000,-0.023000,-0.023000,-0.100,2.000000e-02,-1.000000,3.224000,0.0,0.0
25%,13.823784,3.485368,-0.036000,0.500000,1.100345,1.0,6.000000,2.780000,1.000000,12.000000,...,-0.005000,-0.023000,-0.009000,-0.021500,-0.100,2.000000e-02,-1.000000,10.992000,0.0,0.0
50%,18.759000,4.986176,0.022000,25.500000,189.684780,1.0,12.000000,4.085000,2.000000,16.000000,...,0.016000,0.010500,0.003500,0.012000,-0.045,2.000000e-02,1.000000,15.228000,0.0,0.0
75%,23.807570,9.211665,0.078000,64.000000,433.048395,1.0,12.000000,7.650000,2.000000,24.000000,...,0.037000,0.042000,0.011000,0.047750,0.010,2.000000e-02,1.000000,23.136000,0.0,0.0
max,40.444486,21.015720,0.205000,75.000000,1233.344040,1.0,24.000000,12.520000,5.000000,48.000000,...,0.059000,0.059000,0.050000,0.056000,0.010,2.000000e-02,1.000000,55.872000,0.0,0.0

In [70]:
df_total5.loc[df_total5['P_UNITS'] < 0, 'P_UNITS'] = 0
df_total5.describe()

,P_UNITS,PRICE_R,TOTAL_R,SIZE,PRICE_SIZE,const,Product_Units_Per_Case,Product_CPG_COGS_Price,CASES,UNITS,...,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R,GROUP_R,month_R,randNumCol,UNITS_R,SIZE_16,SIZE_16_PRICE
count,303120.000000,303120.000000,303120.000000,303120.000000,303120.000000,303120.0,303120.000000,303120.000000,303120.000000,303120.000000,...,303120.000000,303120.000000,303120.000000,303120.000000,303120.000,3.031200e+05,303120.000000,303120.000000,303120.0,303120.0
mean,18.875511,6.447082,0.021138,29.611111,272.157866,1.0,10.500000,5.247222,1.819444,17.145833,...,0.015333,0.010944,0.005611,0.014250,-0.045,2.000000e-02,0.001386,17.156737,0.0,0.0
std,7.104763,4.070035,0.076951,27.628310,311.490454,0.0,5.439065,3.231908,0.871246,9.336301,...,0.025138,0.032094,0.021407,0.036465,0.055,1.302675e-13,1.000001,9.455199,0.0,0.0
min,0.000000,1.344288,-0.174000,-8.000000,-43.572800,1.0,3.000000,1.520000,1.000000,4.000000,...,-0.030000,-0.024000,-0.023000,-0.023000,-0.100,2.000000e-02,-1.000000,3.224000,0.0,0.0
25%,13.823784,3.485368,-0.036000,0.500000,1.100345,1.0,6.000000,2.780000,1.000000,12.000000,...,-0.005000,-0.023000,-0.009000,-0.021500,-0.100,2.000000e-02,-1.000000,10.992000,0.0,0.0
50%,18.759000,4.986176,0.022000,25.500000,189.684780,1.0,12.000000,4.085000,2.000000,16.000000,...,0.016000,0.010500,0.003500,0.012000,-0.045,2.000000e-02,1.000000,15.228000,0.0,0.0
75%,23.807570,9.211665,0.078000,64.000000,433.048395,1.0,12.000000,7.650000,2.000000,24.000000,...,0.037000,0.042000,0.011000,0.047750,0.010,2.000000e-02,1.000000,23.136000,0.0,0.0
max,40.444486,21.015720,0.205000,75.000000,1233.344040,1.0,24.000000,12.520000,5.000000,48.000000,...,0.059000,0.059000,0.050000,0.056000,0.010,2.000000e-02,1.000000,55.872000,0.0,0.0

In [71]:
df_total5=df_total5.rename(index=str, columns={"PRICE_R": "PRICE"})

#tips = df_total5.sort_values(['Promo_ID', 'Retailer_Store_ID', 'Product_Unit_UPC'])
df_total5.head()

,P_UNITS,PRICE,TOTAL_R,SIZE,PRICE_SIZE,const,Promo_ID,Retailer_Store_ID,Product_Unit_UPC,TPP_Type,...,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R,GROUP_R,month_R,randNumCol,UNITS_R,SIZE_16,SIZE_16_PRICE
0,27.165711,3.011082,-0.134,64.0,202.85184,1.0,Brandega-18907,12345-94249-107,33404-10164,TPR,...,-0.019,-0.024,0.01,-0.021,-0.1,0.02,-1,27.216,0,0.0
1,27.521342,2.694126,-0.134,64.0,202.85184,1.0,Brandega-18907,12345-94249-107,33404-10164,TPR,...,-0.019,-0.024,0.01,-0.021,-0.1,0.02,-1,27.216,0,0.0
2,26.987896,3.169560,-0.134,64.0,202.85184,1.0,Brandega-18907,12345-94249-107,33404-10164,TPR,...,-0.019,-0.024,0.01,-0.021,-0.1,0.02,-1,27.216,0,0.0
3,27.343526,2.852604,-0.134,64.0,202.85184,1.0,Brandega-18907,12345-94249-107,33404-10164,TPR,...,-0.019,-0.024,0.01,-0.021,-0.1,0.02,-1,27.216,0,0.0
4,27.699157,2.535648,-0.134,64.0,202.85184,1.0,Brandega-18907,12345-94249-107,33404-10164,TPR,...,-0.019,-0.024,0.01,-0.021,-0.1,0.02,-1,27.216,0,0.0

In [72]:
#keep the relevant variables
df_total5 = df_total5[['Promo_ID',
 'Promo_Name',
 'PRICE_POINT',
'Retailer_Name',
 'Retailer_Store_ID',
 'Product_Group_ID',
 'Product_Unit_UPC',
 'Product_Brand',
 'Product_Brand_Category_Desc',
 'Product_Unit_Description',
 'PRICE',
 'TPP_Type',
 'TPP_Start',
 'TPP_End',
 'Product_Units_Per_Case',
 'Product_CPG_COGS_Price',
 'SIZE',
 'CASES',
 'GROUP',
 'UNITS',     
 'P_UNITS']]

In [73]:
#capitalize the field names to load in dash
df_total5=df_total5.rename(str.upper, axis='columns')

In [74]:
df_total5.PRICE_POINT.value_counts(dropna = False).sort_index()

V    60624
W    60624
X    60624
Y    60624
Z    60624
Name: PRICE_POINT, dtype: int64

In [75]:
#De-Dup the file
df_total5=df_total5.drop_duplicates(subset=['PROMO_ID','RETAILER_STORE_ID','PRODUCT_UNIT_UPC','GROUP','PRICE_POINT'], keep='first', inplace=False)
df_total5.shape
df_total5.head()

,PROMO_ID,PROMO_NAME,PRICE_POINT,RETAILER_NAME,RETAILER_STORE_ID,PRODUCT_GROUP_ID,PRODUCT_UNIT_UPC,PRODUCT_BRAND,PRODUCT_BRAND_CATEGORY_DESC,PRODUCT_UNIT_DESCRIPTION,...,TPP_TYPE,TPP_START,TPP_END,PRODUCT_UNITS_PER_CASE,PRODUCT_CPG_COGS_PRICE,SIZE,CASES,GROUP,UNITS,P_UNITS
0,Brandega-18907,Move to the Beat,V,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,...,TPR,2018-01-17,2018-01-26,8.0,2.78,64.0,3.0,ONSALE,24.0,27.165711
1,Brandega-18907,Move to the Beat,W,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,...,TPR,2018-01-17,2018-01-26,8.0,2.78,64.0,3.0,ONSALE,24.0,27.521342
2,Brandega-18907,Move to the Beat,X,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,...,TPR,2018-01-17,2018-01-26,8.0,2.78,64.0,3.0,ONSALE,24.0,26.987896
3,Brandega-18907,Move to the Beat,Y,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,...,TPR,2018-01-17,2018-01-26,8.0,2.78,64.0,3.0,ONSALE,24.0,27.343526
4,Brandega-18907,Move to the Beat,Z,Botann's,12345-94249-107,D-H-C-L-64,33404-10164,Dottie's,Dottie's Cleaners Laundry 64 oz,Dottie's Bleach 64 oz,...,TPR,2018-01-17,2018-01-26,8.0,2.78,64.0,3.0,ONSALE,24.0,27.699157

In [76]:

# @hidden_cell
credentials_1 = {
  'database':'BLUDB',
  'password':"""xxxxxxxxx""",
  'sg_service_url':'https://sgmanager.ng.bluemix.net',
  'host':'dashdb-entry-yp-dal09-08.services.dal.bluemix.net',
  'username':'dash10112',
  'url':'https://undefined'
}

In [77]:
df_load=df_total5

In [78]:
#load records to dashdb

import ibmdbpy
from ibmdbpy import IdaDataBase
idadb = idadb = IdaDataBase(dsn="DASHDB;Database=BLUDB;Hostname=" + credentials_1["host"] + ";PROTOCOL=TCPIP;UID=" + credentials_1["username"] + ";PWD=" + credentials_1["password"])

In [79]:
 idadb.as_idadataframe(df_load, "CLEANERS_FINAL_PRODUCTION",clear_existing = True)

DataFrame will be splitted into 798 chunks. (380 rows per chunk)
Uploaded: 798/798... [DONE]

In [80]:
#spark_df = sqlContext.createDataFrame(df_total5)

In [81]:
#### this inserts records


#from ingest.Connectors import Connectors

#dashdbsaveoption = {
 #                    Connectors.DASHDB.HOST              : 'dashdb-entry-yp-dal09-08.services.dal.bluemix.net',
  #                   Connectors.DASHDB.DATABASE          : 'BLUDB',
   #                  Connectors.DASHDB.USERNAME          : 'dash10112',
    #                 Connectors.DASHDB.PASSWORD          : '-rMyl8IIE1~n',
     #                Connectors.DASHDB.TARGET_TABLE_NAME : 'ICE_CREAM',
      #               Connectors.DASHDB.TARGET_WRITE_MODE : 'merge' }

#spark_df = spark_df.write.format("com.ibm.spark.discover").options(**dashdbsaveoption).save()

In [82]:
#### this deletes then inserts records


#from ingest.Connectors import Connectors

#dashdbsaveoption = {
 #                    Connectors.DASHDB.HOST              : 'dashdb-entry-yp-dal09-08.services.dal.bluemix.net',
  #                   Connectors.DASHDB.DATABASE          : 'BLUDB',
   #                  Connectors.DASHDB.USERNAME          : 'dash10112',
    #                 Connectors.DASHDB.PASSWORD          : '-rMyl8IIE1~n',
     #                Connectors.DASHDB.TARGET_TABLE_NAME : 'DASH10112.ICE_CREAM',
      #               Connectors.DASHDB.TARGET_TABLE_ACTION : 'replace' }

#spark_df = spark_df.write.format("com.ibm.spark.discover").options(**dashdbsaveoption).save()

In [83]:
#This reads records


#from ingest.Connectors import Connectors
#from pyspark.sql import SQLContext
#sqlContext = SQLContext(sc)

#dashDBloadOptions = { Connectors.DASHDB.HOST              : 'dashdb-entry-yp-dal09-08.services.dal.bluemix.net',
 #                     Connectors.DASHDB.DATABASE          : 'BLUDB',
  #                    Connectors.DASHDB.USERNAME          : 'dash10112',
   #                   Connectors.DASHDB.PASSWORD          : '-rMyl8IIE1~n',
    #                  Connectors.DASHDB.SOURCE_TABLE_NAME : 'ICE_CREAM'}

#dashdbDF = sqlContext.read.format("com.ibm.spark.discover").options(**dashDBloadOptions).load()
#dashdbDF.printSchema()
#dashdbDF.show()

In [84]:
#abcd=dashdbDF.toPandas()

In [85]:
#abcd.shape
#abcd.info()