In [1]:
#Establish required libraries

import sys
import types
import pandas as pd 
from botocore.client import Config
import ibm_boto3


import numpy as np
import pandas as pd
from pandas import Series, DataFrame, Index
from IPython.display import Image

def __iter__(self): return 0

import pandas as pd
import numpy as np 

class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

In [2]:
#Establish Libraries and connect to object storage
import sys
import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_e2f5521e5ce34913a7133599cf5a489b = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='xxxxxxxxxxxx',
    ibm_auth_endpoint="https://iam.ng.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_e2f5521e5ce34913a7133599cf5a489b.get_object(Bucket='tradepromotioncampaignevaluation-donotdelete-pr-jezovp3wjfejkl',Key='all products.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_1 = pd.read_csv(body)

df_data_1.info()

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 385636 entries, 0 to 385635
Data columns (total 72 columns):
Demo_Key                                    385636 non-null int64
Promo_ID                                    385636 non-null object
Promo_CPG_Name                              281228 non-null object
Promo_Name                                  385636 non-null object
Retailer_Promo_Contract_ID                  0 non-null float64
Retailer_Name                               385636 non-null object
Retailer_Store_ID                           385636 non-null object
Product_Unit_UPC                            385636 non-null object
Product_Group_ID                            385635 non-null object
Product_Brand                               385636 non-null object
Product_Brand_Category_Desc                 385636 non-null object
Product_Category                            385636 non-null object
Product_Sub_Category                        385636 non-null object
Product_Type                                385636 non-null object
Product_Unit_Description                    385636 non-null object
Retailer_Product_Base_Day_Unit_Volume       385636 non-null float64
Product_CPG_COGS_Price                      385636 non-null float64
Product_Unit_CPG_Retailer_Price             385636 non-null float64
Product_Unit_CPG_Retailer_Discount_Price    385636 non-null float64
Product_Promo_Trade_Investment_Per_Unit     385636 non-null float64
Product_Unit_Retailer_Markup_%              385636 non-null float64
Retailer_Product_Regular_Unit_Price         385636 non-null float64
TPP_Status                                  385636 non-null object
TPP_Discount_%                              385636 non-null float64
TPP_Unit_Sale_Price                         385636 non-null float64
TPP_Baseline_Unit_Volume                    385636 non-null float64
TPP_Start                                   385636 non-null object
TPP_End                                     385636 non-null object
TPP_Duration                                385636 non-null float64
TPP_Type                                    385636 non-null object
Product_Units_Per_Case                      385636 non-null float64
TPP_Baseline_Cases_Volume                   385636 non-null float64
TPP_Baseline_Cost                           385636 non-null float64
TPP_Baseline_Sales_Revenue                  385636 non-null float64
TPP_Baseline_Retailer_Profit                385636 non-null float64
TPP_Baseline_ROI                            385636 non-null float64
TPP_ACV%                                    385635 non-null float64
TPP_Budget                                  385636 non-null float64
TPP_Incremental_Unit_%                      385636 non-null float64
TPP_Incremental_Unit_Volume                 385636 non-null float64
TPP_Incremental_Cases                       385636 non-null float64
TPP_Incremental_Revenue                     385636 non-null float64
TPP_Incremental_Costs                       385636 non-null float64
TPP_Units_Ship                              385636 non-null float64
TPP_Cases_Ship                              385636 non-null float64
TPP_Fixed_Fees                              385636 non-null float64
TPP_Incremental_Variable_Fees               385636 non-null float64
TPP_Total_Fees                              385636 non-null float64
TPP_Comments                                0 non-null float64
TPP_Retailer_ROI%                           385636 non-null float64
TPP_CPG_ROI%                                385636 non-null float64
TPPA_Type                                   385636 non-null object
TPPA_Cost                                   385636 non-null float64
TPPA_Unit_Sale_Price                        385636 non-null float64
TPPA_Discount                               385636 non-null float64
TPPA_Fixed_Fees                             385636 non-null float64
TPPA_Variable_Fees                          385636 non-null float64
TPPA_Total_Fees                             385636 non-null float64
TPPA_Units_Sold                             385636 non-null float64
TPPA_Cases_Sold                             385636 non-null float64
TPPA_Incremental_Cases_Sold                 385636 non-null float64
TPPA_Incremental_Unit_Volume                385636 non-null float64
TPPA_Incremental_Cost                       385636 non-null float64
TPPA_Incremental_Revenue                    385636 non-null float64
TPPA_Incremental_Unit_%                     385636 non-null float64
TPPA_Days_Payment_Due                       385636 non-null float64
TPPA_Days_Payment_Late_Outstanding          385636 non-null float64
TPPA_Payment+Compliance_Calc                385636 non-null object
TPPA_Payment_In_Compliance                  385636 non-null object
TPPA_%ACV                                   385635 non-null float64
TPPA_Retailer_ROI%                          385636 non-null float64
TPPA_CPG_ROI%                               385636 non-null float64
dtypes: float64(51), int64(1), object(20)
memory usage: 211.8+ MB

In [3]:
#select the fields you need
df_price_elasticity = df_data_1[['Promo_ID','Promo_Name','Retailer_Name','Retailer_Store_ID','Product_Category',
                                 'Product_Sub_Category',
                             'Product_Unit_UPC','Product_Group_ID','Product_Brand','Product_Brand_Category_Desc',
                              'Product_Unit_Description','Retailer_Product_Base_Day_Unit_Volume',
                              'TPP_Unit_Sale_Price','Retailer_Product_Regular_Unit_Price','TPP_Incremental_Cases',
                             'TPP_Baseline_Cases_Volume','TPP_Type','TPP_Start','TPP_End','Product_Units_Per_Case','Product_CPG_COGS_Price']]

In [4]:
#Visually inspect the different products in the table
df_price_elasticity.Product_Sub_Category.value_counts(dropna = False).sort_index()

Cereal         67360
Cleaners       30312
Ice Cream      47152
Trail Mix      74096
Vegetables    116196
Yogurt         50520
Name: Product_Sub_Category, dtype: int64

In [5]:
df_price_elasticity.shape

(385636, 21)

In [6]:
#De-Dup the file
df_price_elasticity=df_price_elasticity.drop_duplicates(subset=['Promo_ID','Retailer_Store_ID','Product_Unit_UPC'], keep='first', inplace=False)
df_price_elasticity.shape

(385636, 21)

In [7]:
#remove all products but the one we us

df_price_elasticity=df_price_elasticity[df_price_elasticity['Product_Sub_Category'] =='Vegetables']
df_price_elasticity.shape

(116196, 21)

In [8]:
#create a new field for size
df_price_elasticity['SIZE']=pd.DataFrame(df_price_elasticity['Product_Group_ID'].str[-2:])

In [9]:
df_price_elasticity.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 116196 entries, 117880 to 234075
Data columns (total 22 columns):
Promo_ID                                 116196 non-null object
Promo_Name                               116196 non-null object
Retailer_Name                            116196 non-null object
Retailer_Store_ID                        116196 non-null object
Product_Category                         116196 non-null object
Product_Sub_Category                     116196 non-null object
Product_Unit_UPC                         116196 non-null object
Product_Group_ID                         116196 non-null object
Product_Brand                            116196 non-null object
Product_Brand_Category_Desc              116196 non-null object
Product_Unit_Description                 116196 non-null object
Retailer_Product_Base_Day_Unit_Volume    116196 non-null float64
TPP_Unit_Sale_Price                      116196 non-null float64
Retailer_Product_Regular_Unit_Price      116196 non-null float64
TPP_Incremental_Cases                    116196 non-null float64
TPP_Baseline_Cases_Volume                116196 non-null float64
TPP_Type                                 116196 non-null object
TPP_Start                                116196 non-null object
TPP_End                                  116196 non-null object
Product_Units_Per_Case                   116196 non-null float64
Product_CPG_COGS_Price                   116196 non-null float64
SIZE                                     116196 non-null object
dtypes: float64(7), object(15)
memory usage: 20.4+ MB

In [10]:
#create a copy of the original data set
sale=df_price_elasticity

In [11]:
sale.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 116196 entries, 117880 to 234075
Data columns (total 22 columns):
Promo_ID                                 116196 non-null object
Promo_Name                               116196 non-null object
Retailer_Name                            116196 non-null object
Retailer_Store_ID                        116196 non-null object
Product_Category                         116196 non-null object
Product_Sub_Category                     116196 non-null object
Product_Unit_UPC                         116196 non-null object
Product_Group_ID                         116196 non-null object
Product_Brand                            116196 non-null object
Product_Brand_Category_Desc              116196 non-null object
Product_Unit_Description                 116196 non-null object
Retailer_Product_Base_Day_Unit_Volume    116196 non-null float64
TPP_Unit_Sale_Price                      116196 non-null float64
Retailer_Product_Regular_Unit_Price      116196 non-null float64
TPP_Incremental_Cases                    116196 non-null float64
TPP_Baseline_Cases_Volume                116196 non-null float64
TPP_Type                                 116196 non-null object
TPP_Start                                116196 non-null object
TPP_End                                  116196 non-null object
Product_Units_Per_Case                   116196 non-null float64
Product_CPG_COGS_Price                   116196 non-null float64
SIZE                                     116196 non-null object
dtypes: float64(7), object(15)
memory usage: 20.4+ MB

In [12]:
# create rename the sale price to price, create the cases and units field, drop fields you don't need anymore
#label all of the records as sale records

sale=sale.rename(index=str, columns={"TPP_Unit_Sale_Price": "PRICE"})
sale['CASES'] = sale['TPP_Baseline_Cases_Volume'] + sale['TPP_Incremental_Cases'] 
sale['GROUP']='ONSALE'
sale['UNITS']=sale['CASES']*sale['Product_Units_Per_Case']
sale=sale.drop(['TPP_Baseline_Cases_Volume', 'TPP_Incremental_Cases','Retailer_Product_Regular_Unit_Price','Retailer_Product_Base_Day_Unit_Volume'], axis=1)

In [13]:
sale.info()

<class 'pandas.core.frame.DataFrame'>
Index: 116196 entries, 117880 to 234075
Data columns (total 21 columns):
Promo_ID                       116196 non-null object
Promo_Name                     116196 non-null object
Retailer_Name                  116196 non-null object
Retailer_Store_ID              116196 non-null object
Product_Category               116196 non-null object
Product_Sub_Category           116196 non-null object
Product_Unit_UPC               116196 non-null object
Product_Group_ID               116196 non-null object
Product_Brand                  116196 non-null object
Product_Brand_Category_Desc    116196 non-null object
Product_Unit_Description       116196 non-null object
PRICE                          116196 non-null float64
TPP_Type                       116196 non-null object
TPP_Start                      116196 non-null object
TPP_End                        116196 non-null object
Product_Units_Per_Case         116196 non-null float64
Product_CPG_COGS_Price         116196 non-null float64
SIZE                           116196 non-null object
CASES                          116196 non-null float64
GROUP                          116196 non-null object
UNITS                          116196 non-null float64
dtypes: float64(5), object(16)
memory usage: 19.5+ MB

In [14]:
#copy the orginal data set, create the non-sale prices
nosale=df_price_elasticity

In [15]:
nosale.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 116196 entries, 117880 to 234075
Data columns (total 22 columns):
Promo_ID                                 116196 non-null object
Promo_Name                               116196 non-null object
Retailer_Name                            116196 non-null object
Retailer_Store_ID                        116196 non-null object
Product_Category                         116196 non-null object
Product_Sub_Category                     116196 non-null object
Product_Unit_UPC                         116196 non-null object
Product_Group_ID                         116196 non-null object
Product_Brand                            116196 non-null object
Product_Brand_Category_Desc              116196 non-null object
Product_Unit_Description                 116196 non-null object
Retailer_Product_Base_Day_Unit_Volume    116196 non-null float64
TPP_Unit_Sale_Price                      116196 non-null float64
Retailer_Product_Regular_Unit_Price      116196 non-null float64
TPP_Incremental_Cases                    116196 non-null float64
TPP_Baseline_Cases_Volume                116196 non-null float64
TPP_Type                                 116196 non-null object
TPP_Start                                116196 non-null object
TPP_End                                  116196 non-null object
Product_Units_Per_Case                   116196 non-null float64
Product_CPG_COGS_Price                   116196 non-null float64
SIZE                                     116196 non-null object
dtypes: float64(7), object(15)
memory usage: 20.4+ MB

In [16]:
#create the cases and price field
nosale=nosale.rename(index=str, columns={"TPP_Baseline_Cases_Volume": "CASES", "Retailer_Product_Regular_Unit_Price":"PRICE"})

In [17]:
nosale.info()

<class 'pandas.core.frame.DataFrame'>
Index: 116196 entries, 117880 to 234075
Data columns (total 22 columns):
Promo_ID                                 116196 non-null object
Promo_Name                               116196 non-null object
Retailer_Name                            116196 non-null object
Retailer_Store_ID                        116196 non-null object
Product_Category                         116196 non-null object
Product_Sub_Category                     116196 non-null object
Product_Unit_UPC                         116196 non-null object
Product_Group_ID                         116196 non-null object
Product_Brand                            116196 non-null object
Product_Brand_Category_Desc              116196 non-null object
Product_Unit_Description                 116196 non-null object
Retailer_Product_Base_Day_Unit_Volume    116196 non-null float64
TPP_Unit_Sale_Price                      116196 non-null float64
PRICE                                    116196 non-null float64
TPP_Incremental_Cases                    116196 non-null float64
CASES                                    116196 non-null float64
TPP_Type                                 116196 non-null object
TPP_Start                                116196 non-null object
TPP_End                                  116196 non-null object
Product_Units_Per_Case                   116196 non-null float64
Product_CPG_COGS_Price                   116196 non-null float64
SIZE                                     116196 non-null object
dtypes: float64(7), object(15)
memory usage: 20.4+ MB

In [18]:
#Calculate the number of Units
nosale['UNITS']=nosale['CASES']*nosale['Product_Units_Per_Case']

In [19]:
#identify the prices as non-sale prices.
nosale['GROUP']='NOTONSALE'


#Remove stuff you don't need


nosale=nosale.drop([ 'TPP_Incremental_Cases','TPP_Unit_Sale_Price','Retailer_Product_Base_Day_Unit_Volume','TPP_Type'], axis=1)
nosale['TPP_Type']='N'

In [20]:
nosale.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Category,Product_Sub_Category,Product_Unit_UPC,Product_Group_ID,Product_Brand,Product_Brand_Category_Desc,...,PRICE,CASES,TPP_Start,TPP_End,Product_Units_Per_Case,Product_CPG_COGS_Price,SIZE,UNITS,GROUP,TPP_Type
117880,Brandega-17919,Back to School,Botann's,12345-94249-107,Frozen,Vegetables,66335-40120,GD-F-V-S-20,Garden Delights,Garden Delights Vegetables Simple 20 oz,...,4.69,1.0,2019-08-26,2019-09-04,24.0,3.38,20,24.0,NOTONSALE,N
117881,Brandega-17919,Back to School,Botann's,12345-94249-107,Frozen,Vegetables,66335-40220,GD-F-V-S-20,Garden Delights,Garden Delights Vegetables Simple 20 oz,...,4.69,1.0,2019-08-26,2019-09-04,24.0,3.38,20,24.0,NOTONSALE,N
117882,Brandega-17919,Back to School,Botann's,12345-94249-107,Frozen,Vegetables,66335-40320,GD-F-V-S-20,Garden Delights,Garden Delights Vegetables Simple 20 oz,...,4.69,1.0,2019-08-26,2019-09-04,24.0,3.38,20,24.0,NOTONSALE,N
117883,Brandega-17919,Back to School,Botann's,12345-94249-107,Frozen,Vegetables,66335-40420,GD-F-V-S-20,Garden Delights,Garden Delights Vegetables Simple 20 oz,...,4.69,1.0,2019-08-26,2019-09-04,24.0,3.38,20,24.0,NOTONSALE,N
117884,Brandega-17919,Back to School,Botann's,12345-94249-107,Frozen,Vegetables,66335-40520,GD-F-V-S-20,Garden Delights,Garden Delights Vegetables Simple 20 oz,...,4.69,1.0,2019-08-26,2019-09-04,24.0,3.38,20,24.0,NOTONSALE,N

In [21]:
sale.info()
nosale.info()

<class 'pandas.core.frame.DataFrame'>
Index: 116196 entries, 117880 to 234075
Data columns (total 21 columns):
Promo_ID                       116196 non-null object
Promo_Name                     116196 non-null object
Retailer_Name                  116196 non-null object
Retailer_Store_ID              116196 non-null object
Product_Category               116196 non-null object
Product_Sub_Category           116196 non-null object
Product_Unit_UPC               116196 non-null object
Product_Group_ID               116196 non-null object
Product_Brand                  116196 non-null object
Product_Brand_Category_Desc    116196 non-null object
Product_Unit_Description       116196 non-null object
PRICE                          116196 non-null float64
TPP_Type                       116196 non-null object
TPP_Start                      116196 non-null object
TPP_End                        116196 non-null object
Product_Units_Per_Case         116196 non-null float64
Product_CPG_COGS_Price         116196 non-null float64
SIZE                           116196 non-null object
CASES                          116196 non-null float64
GROUP                          116196 non-null object
UNITS                          116196 non-null float64
dtypes: float64(5), object(16)
memory usage: 19.5+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 116196 entries, 117880 to 234075
Data columns (total 21 columns):
Promo_ID                       116196 non-null object
Promo_Name                     116196 non-null object
Retailer_Name                  116196 non-null object
Retailer_Store_ID              116196 non-null object
Product_Category               116196 non-null object
Product_Sub_Category           116196 non-null object
Product_Unit_UPC               116196 non-null object
Product_Group_ID               116196 non-null object
Product_Brand                  116196 non-null object
Product_Brand_Category_Desc    116196 non-null object
Product_Unit_Description       116196 non-null object
PRICE                          116196 non-null float64
CASES                          116196 non-null float64
TPP_Start                      116196 non-null object
TPP_End                        116196 non-null object
Product_Units_Per_Case         116196 non-null float64
Product_CPG_COGS_Price         116196 non-null float64
SIZE                           116196 non-null object
UNITS                          116196 non-null float64
GROUP                          116196 non-null object
TPP_Type                       116196 non-null object
dtypes: float64(5), object(16)
memory usage: 19.5+ MB

In [22]:
#include needed fields
nosale = nosale[['Promo_ID',
 'Promo_Name',
 'Retailer_Name',
 'Retailer_Store_ID',
 'Product_Group_ID',
 'Product_Unit_UPC',
 'Product_Brand',
 'Product_Brand_Category_Desc',
 'Product_Unit_Description',
 'PRICE',
 'TPP_Type',
 'TPP_Start',
 'TPP_End',
 'Product_Units_Per_Case',
 'Product_CPG_COGS_Price',
 'SIZE',
 'CASES',
 'GROUP',
 'UNITS']]

In [23]:
#include needed fields
sale = sale[['Promo_ID',
 'Promo_Name',
 'Retailer_Name',
 'Retailer_Store_ID',
 'Product_Group_ID',
 'Product_Unit_UPC',
 'Product_Brand',
 'Product_Brand_Category_Desc',
 'Product_Unit_Description',
 'PRICE',
 'TPP_Type',
 'TPP_Start',
 'TPP_End',
 'Product_Units_Per_Case',
 'Product_CPG_COGS_Price',
 'SIZE',
 'CASES',
 'GROUP',
 'UNITS']]

In [24]:
sale.info()
nosale.info()

<class 'pandas.core.frame.DataFrame'>
Index: 116196 entries, 117880 to 234075
Data columns (total 19 columns):
Promo_ID                       116196 non-null object
Promo_Name                     116196 non-null object
Retailer_Name                  116196 non-null object
Retailer_Store_ID              116196 non-null object
Product_Group_ID               116196 non-null object
Product_Unit_UPC               116196 non-null object
Product_Brand                  116196 non-null object
Product_Brand_Category_Desc    116196 non-null object
Product_Unit_Description       116196 non-null object
PRICE                          116196 non-null float64
TPP_Type                       116196 non-null object
TPP_Start                      116196 non-null object
TPP_End                        116196 non-null object
Product_Units_Per_Case         116196 non-null float64
Product_CPG_COGS_Price         116196 non-null float64
SIZE                           116196 non-null object
CASES                          116196 non-null float64
GROUP                          116196 non-null object
UNITS                          116196 non-null float64
dtypes: float64(5), object(14)
memory usage: 17.7+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 116196 entries, 117880 to 234075
Data columns (total 19 columns):
Promo_ID                       116196 non-null object
Promo_Name                     116196 non-null object
Retailer_Name                  116196 non-null object
Retailer_Store_ID              116196 non-null object
Product_Group_ID               116196 non-null object
Product_Unit_UPC               116196 non-null object
Product_Brand                  116196 non-null object
Product_Brand_Category_Desc    116196 non-null object
Product_Unit_Description       116196 non-null object
PRICE                          116196 non-null float64
TPP_Type                       116196 non-null object
TPP_Start                      116196 non-null object
TPP_End                        116196 non-null object
Product_Units_Per_Case         116196 non-null float64
Product_CPG_COGS_Price         116196 non-null float64
SIZE                           116196 non-null object
CASES                          116196 non-null float64
GROUP                          116196 non-null object
UNITS                          116196 non-null float64
dtypes: float64(5), object(14)
memory usage: 17.7+ MB

In [25]:
#append the sale and non-sale records into one dataframe
df_total=pd.DataFrame(sale.append(nosale, ignore_index=True, verify_integrity=False))

In [26]:
#convert the tpp_start which is character to a pandas date field
df_total['date'] = pd.to_datetime(df_total['TPP_Start'])
df_total.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,TPP_Type,TPP_Start,TPP_End,Product_Units_Per_Case,Product_CPG_COGS_Price,SIZE,CASES,GROUP,UNITS,date
0,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,TPR,2019-08-26,2019-09-04,24.0,3.38,20,2.0,ONSALE,48.0,2019-08-26
1,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40220,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Deluxe Stir-Fry 20 oz,4.17,TPR,2019-08-26,2019-09-04,24.0,3.38,20,2.0,ONSALE,48.0,2019-08-26
2,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40320,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Pepper and Onion Blend 20 oz,4.17,TPR,2019-08-26,2019-09-04,24.0,3.38,20,2.0,ONSALE,48.0,2019-08-26
3,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40420,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Broccoli Stir-Fry 20 oz,4.17,TPR,2019-08-26,2019-09-04,24.0,3.38,20,2.0,ONSALE,48.0,2019-08-26
4,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40520,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Broccoli 20 oz,4.17,TPR,2019-08-26,2019-09-04,24.0,3.38,20,2.0,ONSALE,48.0,2019-08-26

In [27]:
#create a field for year and month
df_total['year'], df_total['month'] = df_total['date'].dt.year, df_total['date'].dt.month
df_total.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,TPP_End,Product_Units_Per_Case,Product_CPG_COGS_Price,SIZE,CASES,GROUP,UNITS,date,year,month
0,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-09-04,24.0,3.38,20,2.0,ONSALE,48.0,2019-08-26,2019,8
1,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40220,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Deluxe Stir-Fry 20 oz,4.17,...,2019-09-04,24.0,3.38,20,2.0,ONSALE,48.0,2019-08-26,2019,8
2,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40320,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Pepper and Onion Blend 20 oz,4.17,...,2019-09-04,24.0,3.38,20,2.0,ONSALE,48.0,2019-08-26,2019,8
3,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40420,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Broccoli Stir-Fry 20 oz,4.17,...,2019-09-04,24.0,3.38,20,2.0,ONSALE,48.0,2019-08-26,2019,8
4,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40520,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Broccoli 20 oz,4.17,...,2019-09-04,24.0,3.38,20,2.0,ONSALE,48.0,2019-08-26,2019,8

In [28]:
#assign random numbers to each retailer
wookie = pd.DataFrame(df_total.groupby(['Retailer_Store_ID'])['PRICE'].mean())
wookie=wookie.drop(['PRICE'], axis=1)

In [29]:
wookie['Retailer_R'] = (np.random.randint(-30, 60, wookie.shape[0]))/1000
wookie.reset_index(level=0, inplace=True)
wookie.head()

  Retailer_Store_ID  Retailer_R
0   12345-10024-126       0.019
1   12345-14213-136       0.058
2   12345-14601-157      -0.010
3   12345-15225-129       0.043
4   12345-15225-167       0.014

In [30]:
df_total1 =df_total.merge(wookie, on=['Retailer_Store_ID'], how='inner')
df_total1.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,Product_Units_Per_Case,Product_CPG_COGS_Price,SIZE,CASES,GROUP,UNITS,date,year,month,Retailer_R
0,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,24.0,3.38,20,2.0,ONSALE,48.0,2019-08-26,2019,8,0.0
1,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40220,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Deluxe Stir-Fry 20 oz,4.17,...,24.0,3.38,20,2.0,ONSALE,48.0,2019-08-26,2019,8,0.0
2,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40320,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Pepper and Onion Blend 20 oz,4.17,...,24.0,3.38,20,2.0,ONSALE,48.0,2019-08-26,2019,8,0.0
3,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40420,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Broccoli Stir-Fry 20 oz,4.17,...,24.0,3.38,20,2.0,ONSALE,48.0,2019-08-26,2019,8,0.0
4,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40520,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Broccoli 20 oz,4.17,...,24.0,3.38,20,2.0,ONSALE,48.0,2019-08-26,2019,8,0.0

In [31]:
#assign random numbers to each product group id
df_total1.Product_Group_ID.value_counts(dropna = False).sort_index()

GD-F-V-FS-64    77464
GD-F-V-S-20     77464
GD-F-V-S-32     77464
Name: Product_Group_ID, dtype: int64

In [32]:
 wookie = pd.DataFrame(df_total1.groupby(['Product_Group_ID'])['PRICE'].mean())
wookie=wookie.drop(['PRICE'], axis=1)

In [33]:
wookie['PRODUCT_GROUP_ID_R'] = (np.random.randint(-30, 60, wookie.shape[0]))/1000
wookie.reset_index(level=0, inplace=True)
wookie.head()

  Product_Group_ID  PRODUCT_GROUP_ID_R
0     GD-F-V-FS-64               0.011
1      GD-F-V-S-20               0.000
2      GD-F-V-S-32               0.022

In [34]:
#!pip install plotly --upgrade

In [35]:
df_total2 =df_total1.merge(wookie, on=['Product_Group_ID'], how='inner')
df_total2.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,Product_CPG_COGS_Price,SIZE,CASES,GROUP,UNITS,date,year,month,Retailer_R,PRODUCT_GROUP_ID_R
0,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,3.38,20,2.0,ONSALE,48.0,2019-08-26,2019,8,0.0,0.0
1,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40220,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Deluxe Stir-Fry 20 oz,4.17,...,3.38,20,2.0,ONSALE,48.0,2019-08-26,2019,8,0.0,0.0
2,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40320,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Pepper and Onion Blend 20 oz,4.17,...,3.38,20,2.0,ONSALE,48.0,2019-08-26,2019,8,0.0,0.0
3,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40420,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Broccoli Stir-Fry 20 oz,4.17,...,3.38,20,2.0,ONSALE,48.0,2019-08-26,2019,8,0.0,0.0
4,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40520,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Broccoli 20 oz,4.17,...,3.38,20,2.0,ONSALE,48.0,2019-08-26,2019,8,0.0,0.0

In [36]:
#assign random numbers to each product unit upc value
df_total2.Product_Unit_UPC.value_counts(dropna = False).sort_index()

66335-40120    3368
66335-40220    3368
66335-40320    3368
66335-40420    3368
66335-40520    3368
66335-40620    3368
66335-40720    3368
66335-40820    3368
66335-40920    3368
66335-41020    3368
66335-41120    3368
66335-41220    3368
66335-41320    3368
66335-41420    3368
66335-41520    3368
66335-41620    3368
66335-41720    3368
66335-41820    3368
66335-41920    3368
66335-42020    3368
66335-42120    3368
66335-42220    3368
66335-42320    3368
66435-42432    3368
66435-42532    3368
66435-42632    3368
66435-42732    3368
66435-42832    3368
66435-42932    3368
66435-43032    3368
               ...
66435-44032    3368
66435-44132    3368
66435-44232    3368
66435-44332    3368
66435-44432    3368
66435-44532    3368
66435-44632    3368
66535-44764    3368
66535-44864    3368
66535-44964    3368
66535-45064    3368
66535-45164    3368
66535-45264    3368
66535-45364    3368
66535-45464    3368
66535-45564    3368
66535-45664    3368
66535-45764    3368
66535-45864    3368
66535-45964    3368
66535-46064    3368
66535-46164    3368
66535-46264    3368
66535-46364    3368
66535-46464    3368
66535-46564    3368
66535-46664    3368
66535-46764    3368
66535-46864    3368
66535-46964    3368
Name: Product_Unit_UPC, Length: 69, dtype: int64

In [37]:
wookie = pd.DataFrame(df_total2.groupby(['Product_Unit_UPC'])['PRICE'].mean())
wookie=wookie.drop(['PRICE'], axis=1)

wookie['Product_Unit_UPC_R'] = (np.random.randint(-30, 60, wookie.shape[0]))/1000
wookie.reset_index(level=0, inplace=True)
wookie.head()
df_total3 =df_total2.merge(wookie, on=['Product_Unit_UPC'], how='inner')
df_total3.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,SIZE,CASES,GROUP,UNITS,date,year,month,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R
0,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,20,2.0,ONSALE,48.0,2019-08-26,2019,8,0.0,0.0,0.012
1,Brandega-46224,Winter Follie,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.31,...,20,2.0,ONSALE,48.0,2019-01-30,2019,1,0.0,0.0,0.012
2,Brandega-52181,Just Chillin',Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.10,...,20,2.0,ONSALE,48.0,2019-06-15,2019,6,0.0,0.0,0.012
3,Brandega-62311,Low Cal Delights,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,3.98,...,20,2.0,ONSALE,48.0,2019-03-13,2019,3,0.0,0.0,0.012
4,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,20,1.0,NOTONSALE,24.0,2019-08-26,2019,8,0.0,0.0,0.012

In [38]:
#assign random numbers to each promo
df_total2.Promo_Name.value_counts(dropna = False).sort_index()

Back to School       58098
Just Chillin'        58098
Low Cal Delights     58098
Winter Follie        58098
Name: Promo_Name, dtype: int64

In [39]:
wookie = pd.DataFrame(df_total3.groupby(['Promo_Name'])['PRICE'].mean())
wookie=wookie.drop(['PRICE'], axis=1)

wookie['Promo_Name_R'] = (np.random.randint(-30, 60, wookie.shape[0]))/1000
wookie.reset_index(level=0, inplace=True)
wookie.head()
df_total4 =df_total3.merge(wookie, on=['Promo_Name'], how='inner')
df_total4.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,CASES,GROUP,UNITS,date,year,month,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R
0,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2.0,ONSALE,48.0,2019-08-26,2019,8,0.000,0.0,0.012,0.043
1,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,1.0,NOTONSALE,24.0,2019-08-26,2019,8,0.000,0.0,0.012,0.043
2,Brandega-17919,Back to School,Botann's,12345-79914-108,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2.0,ONSALE,48.0,2019-08-26,2019,8,0.050,0.0,0.012,0.043
3,Brandega-17919,Back to School,Botann's,12345-79914-108,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,1.0,NOTONSALE,24.0,2019-08-26,2019,8,0.050,0.0,0.012,0.043
4,Brandega-17919,Back to School,Botann's,12345-90005-109,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2.0,ONSALE,48.0,2019-08-26,2019,8,-0.023,0.0,0.012,0.043

In [40]:
#assign different values to sale and non-sale records
df_total4['GROUP_R'] = np.where(df_total4['GROUP'] == 'ONSALE', -0.10, 0.01)
df_total4.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,GROUP,UNITS,date,year,month,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R,GROUP_R
0,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,ONSALE,48.0,2019-08-26,2019,8,0.000,0.0,0.012,0.043,-0.10
1,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,NOTONSALE,24.0,2019-08-26,2019,8,0.000,0.0,0.012,0.043,0.01
2,Brandega-17919,Back to School,Botann's,12345-79914-108,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,ONSALE,48.0,2019-08-26,2019,8,0.050,0.0,0.012,0.043,-0.10
3,Brandega-17919,Back to School,Botann's,12345-79914-108,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,NOTONSALE,24.0,2019-08-26,2019,8,0.050,0.0,0.012,0.043,0.01
4,Brandega-17919,Back to School,Botann's,12345-90005-109,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,ONSALE,48.0,2019-08-26,2019,8,-0.023,0.0,0.012,0.043,-0.10

In [41]:
df_total4.month.value_counts(dropna = False).sort_index()

1    58098
3    58098
6    58098
8    58098
Name: month, dtype: int64

In [42]:
#assign values to each month
conditions = [
    (df_total4['month'] == 2),
    (df_total4['month'] ==4),
    (df_total4['month'] ==7)]
choices = [-0.03, 0.02, 0.06]
df_total4['month_R'] = np.select(conditions, choices, default=0.02)

In [43]:
df_total4.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,UNITS,date,year,month,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R,GROUP_R,month_R
0,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,48.0,2019-08-26,2019,8,0.000,0.0,0.012,0.043,-0.10,0.02
1,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,24.0,2019-08-26,2019,8,0.000,0.0,0.012,0.043,0.01,0.02
2,Brandega-17919,Back to School,Botann's,12345-79914-108,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,48.0,2019-08-26,2019,8,0.050,0.0,0.012,0.043,-0.10,0.02
3,Brandega-17919,Back to School,Botann's,12345-79914-108,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,24.0,2019-08-26,2019,8,0.050,0.0,0.012,0.043,0.01,0.02
4,Brandega-17919,Back to School,Botann's,12345-90005-109,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,48.0,2019-08-26,2019,8,-0.023,0.0,0.012,0.043,-0.10,0.02

In [44]:
#generate a random number for each row that is either 1 or -1
import random
df_total4['randNumCol'] = np.random.choice([1, -1], df_total4.shape[0])
df_total4.head(100)

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,date,year,month,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R,GROUP_R,month_R,randNumCol
0,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.000,0.0,0.012,0.043,-0.10,0.02,1
1,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.000,0.0,0.012,0.043,0.01,0.02,1
2,Brandega-17919,Back to School,Botann's,12345-79914-108,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.050,0.0,0.012,0.043,-0.10,0.02,1
3,Brandega-17919,Back to School,Botann's,12345-79914-108,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.050,0.0,0.012,0.043,0.01,0.02,-1
4,Brandega-17919,Back to School,Botann's,12345-90005-109,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,-0.023,0.0,0.012,0.043,-0.10,0.02,1
5,Brandega-17919,Back to School,Botann's,12345-90005-109,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,-0.023,0.0,0.012,0.043,0.01,0.02,1
6,Brandega-17919,Back to School,Botann's,12345-33233-110,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,-0.029,0.0,0.012,0.043,-0.10,0.02,-1
7,Brandega-17919,Back to School,Botann's,12345-33233-110,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,-0.029,0.0,0.012,0.043,0.01,0.02,-1
8,Brandega-17919,Back to School,Botann's,12345-28816-111,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.016,0.0,0.012,0.043,-0.10,0.02,-1
9,Brandega-17919,Back to School,Botann's,12345-28816-111,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.016,0.0,0.012,0.043,0.01,0.02,-1
10,Brandega-17919,Back to School,Botann's,12345-80524-112,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,-0.021,0.0,0.012,0.043,-0.10,0.02,1
11,Brandega-17919,Back to School,Botann's,12345-80524-112,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,-0.021,0.0,0.012,0.043,0.01,0.02,1
12,Brandega-17919,Back to School,Botann's,12345-78766-113,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.033,0.0,0.012,0.043,-0.10,0.02,1
13,Brandega-17919,Back to School,Botann's,12345-78766-113,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.033,0.0,0.012,0.043,0.01,0.02,1
14,Brandega-17919,Back to School,Botann's,12345-78224-114,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.058,0.0,0.012,0.043,-0.10,0.02,-1
15,Brandega-17919,Back to School,Botann's,12345-78224-114,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.058,0.0,0.012,0.043,0.01,0.02,-1
16,Brandega-17919,Back to School,Botann's,12345-92102-115,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.014,0.0,0.012,0.043,-0.10,0.02,-1
17,Brandega-17919,Back to School,Botann's,12345-92102-115,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.014,0.0,0.012,0.043,0.01,0.02,-1
18,Brandega-17919,Back to School,Botann's,12345-90005-116,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.017,0.0,0.012,0.043,-0.10,0.02,1
19,Brandega-17919,Back to School,Botann's,12345-90005-116,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.017,0.0,0.012,0.043,0.01,0.02,1
20,Brandega-17919,Back to School,Botann's,12345-28816-117,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,-0.020,0.0,0.012,0.043,-0.10,0.02,1
21,Brandega-17919,Back to School,Botann's,12345-28816-117,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,-0.020,0.0,0.012,0.043,0.01,0.02,1
22,Brandega-17919,Back to School,Botann's,12345-22336-118,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.004,0.0,0.012,0.043,-0.10,0.02,-1
23,Brandega-17919,Back to School,Botann's,12345-22336-118,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.004,0.0,0.012,0.043,0.01,0.02,-1
24,Brandega-17919,Back to School,Botann's,12345-75240-119,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,-0.013,0.0,0.012,0.043,-0.10,0.02,1
25,Brandega-17919,Back to School,Botann's,12345-75240-119,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,-0.013,0.0,0.012,0.043,0.01,0.02,1
26,Brandega-17919,Back to School,Botann's,12345-90005-120,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.056,0.0,0.012,0.043,-0.10,0.02,1
27,Brandega-17919,Back to School,Botann's,12345-90005-120,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.056,0.0,0.012,0.043,0.01,0.02,-1
28,Brandega-17919,Back to School,Botann's,12345-78224-121,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,-0.018,0.0,0.012,0.043,-0.10,0.02,1
29,Brandega-17919,Back to School,Botann's,12345-78224-121,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,-0.018,0.0,0.012,0.043,0.01,0.02,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,Brandega-17919,Back to School,Botann's,12345-73502-142,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,-0.016,0.0,0.012,0.043,-0.10,0.02,-1
71,Brandega-17919,Back to School,Botann's,12345-73502-142,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,-0.016,0.0,0.012,0.043,0.01,0.02,1
72,Brandega-17919,Back to School,Botann's,12345-32277-143,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,-0.004,0.0,0.012,0.043,-0.10,0.02,1
73,Brandega-17919,Back to School,Botann's,12345-32277-143,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,-0.004,0.0,0.012,0.043,0.01,0.02,-1
74,Brandega-17919,Back to School,Botann's,12345-65616-144,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.000,0.0,0.012,0.043,-0.10,0.02,1
75,Brandega-17919,Back to School,Botann's,12345-65616-144,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.000,0.0,0.012,0.043,0.01,0.02,-1
76,Brandega-17919,Back to School,Botann's,12345-26003-145,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.010,0.0,0.012,0.043,-0.10,0.02,1
77,Brandega-17919,Back to School,Botann's,12345-26003-145,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.010,0.0,0.012,0.043,0.01,0.02,1
78,Brandega-17919,Back to School,Botann's,12345-22336-146,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.049,0.0,0.012,0.043,-0.10,0.02,-1
79,Brandega-17919,Back to School,Botann's,12345-22336-146,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.049,0.0,0.012,0.043,0.01,0.02,-1
80,Brandega-17919,Back to School,Botann's,12345-32550-147,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,-0.021,0.0,0.012,0.043,-0.10,0.02,-1
81,Brandega-17919,Back to School,Botann's,12345-32550-147,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,-0.021,0.0,0.012,0.043,0.01,0.02,1
82,Brandega-17919,Back to School,Botann's,12345-78224-148,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.000,0.0,0.012,0.043,-0.10,0.02,-1
83,Brandega-17919,Back to School,Botann's,12345-78224-148,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.000,0.0,0.012,0.043,0.01,0.02,1
84,Brandega-17919,Back to School,Botann's,12345-94104-149,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.044,0.0,0.012,0.043,-0.10,0.02,-1
85,Brandega-17919,Back to School,Botann's,12345-94104-149,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.044,0.0,0.012,0.043,0.01,0.02,1
86,Brandega-17919,Back to School,Botann's,12345-94249-150,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,-0.005,0.0,0.012,0.043,-0.10,0.02,-1
87,Brandega-17919,Back to School,Botann's,12345-94249-150,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,-0.005,0.0,0.012,0.043,0.01,0.02,1
88,Brandega-17919,Back to School,Botann's,12345-85261-151,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.045,0.0,0.012,0.043,-0.10,0.02,-1
89,Brandega-17919,Back to School,Botann's,12345-85261-151,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.045,0.0,0.012,0.043,0.01,0.02,-1
90,Brandega-17919,Back to School,Botann's,12345-37421-152,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.028,0.0,0.012,0.043,-0.10,0.02,1
91,Brandega-17919,Back to School,Botann's,12345-37421-152,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.028,0.0,0.012,0.043,0.01,0.02,-1
92,Brandega-17919,Back to School,Botann's,12345-53284-153,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.014,0.0,0.012,0.043,-0.10,0.02,1
93,Brandega-17919,Back to School,Botann's,12345-53284-153,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.014,0.0,0.012,0.043,0.01,0.02,-1
94,Brandega-17919,Back to School,Botann's,12345-79914-154,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.025,0.0,0.012,0.043,-0.10,0.02,1
95,Brandega-17919,Back to School,Botann's,12345-79914-154,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.025,0.0,0.012,0.043,0.01,0.02,-1
96,Brandega-17919,Back to School,Botann's,12345-65110-155,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.044,0.0,0.012,0.043,-0.10,0.02,1
97,Brandega-17919,Back to School,Botann's,12345-65110-155,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.044,0.0,0.012,0.043,0.01,0.02,1
98,Brandega-17919,Back to School,Botann's,12345-48206-156,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019-08-26,2019,8,0.006,0.0,0.012,0.043,-0.10,0.02,-1
99,Brandega-17919,Back to School,Botann's,12345-48206-156,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019-08-26,2019,8,0.006,0.0,0.012,0.043,0.01,0.02,-1

In [45]:
#sum the generated numbers for each row, making a unique value for each row called total_r

cols = ['Retailer_R','PRODUCT_GROUP_ID_R','Product_Unit_UPC_R','Promo_Name_R','GROUP_R','month_R']
df_total4['TOTAL_R'] = df_total4[cols].astype(float).sum(axis=1)

In [46]:
df_total4.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,year,month,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R,GROUP_R,month_R,randNumCol,TOTAL_R
0,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019,8,0.000,0.0,0.012,0.043,-0.10,0.02,1,-0.025
1,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019,8,0.000,0.0,0.012,0.043,0.01,0.02,1,0.085
2,Brandega-17919,Back to School,Botann's,12345-79914-108,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019,8,0.050,0.0,0.012,0.043,-0.10,0.02,1,0.025
3,Brandega-17919,Back to School,Botann's,12345-79914-108,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,2019,8,0.050,0.0,0.012,0.043,0.01,0.02,-1,0.135
4,Brandega-17919,Back to School,Botann's,12345-90005-109,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,2019,8,-0.023,0.0,0.012,0.043,-0.10,0.02,1,-0.048

In [47]:
df_total4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 232392 entries, 0 to 232391
Data columns (total 30 columns):
Promo_ID                       232392 non-null object
Promo_Name                     232392 non-null object
Retailer_Name                  232392 non-null object
Retailer_Store_ID              232392 non-null object
Product_Group_ID               232392 non-null object
Product_Unit_UPC               232392 non-null object
Product_Brand                  232392 non-null object
Product_Brand_Category_Desc    232392 non-null object
Product_Unit_Description       232392 non-null object
PRICE                          232392 non-null float64
TPP_Type                       232392 non-null object
TPP_Start                      232392 non-null object
TPP_End                        232392 non-null object
Product_Units_Per_Case         232392 non-null float64
Product_CPG_COGS_Price         232392 non-null float64
SIZE                           232392 non-null object
CASES                          232392 non-null float64
GROUP                          232392 non-null object
UNITS                          232392 non-null float64
date                           232392 non-null datetime64[ns]
year                           232392 non-null int64
month                          232392 non-null int64
Retailer_R                     232392 non-null float64
PRODUCT_GROUP_ID_R             232392 non-null float64
Product_Unit_UPC_R             232392 non-null float64
Promo_Name_R                   232392 non-null float64
GROUP_R                        232392 non-null float64
month_R                        232392 non-null float64
randNumCol                     232392 non-null int64
TOTAL_R                        232392 non-null float64
dtypes: datetime64[ns](1), float64(12), int64(3), object(14)
memory usage: 55.0+ MB

In [48]:
#create new prices based on the adjustment numbers generated on the previous lines
df_total4['PRICE_R']=df_total4['PRICE']*(1.0-(df_total4['randNumCol']*df_total4['TOTAL_R']))
df_total4['UNITS_R']=df_total4['UNITS']*(1.0+(df_total4['randNumCol']*df_total4['TOTAL_R']))

In [49]:
df_total4.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R,GROUP_R,month_R,randNumCol,TOTAL_R,PRICE_R,UNITS_R
0,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,0.000,0.0,0.012,0.043,-0.10,0.02,1,-0.025,4.27425,46.800
1,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,0.000,0.0,0.012,0.043,0.01,0.02,1,0.085,4.29135,26.040
2,Brandega-17919,Back to School,Botann's,12345-79914-108,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,0.050,0.0,0.012,0.043,-0.10,0.02,1,0.025,4.06575,49.200
3,Brandega-17919,Back to School,Botann's,12345-79914-108,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,0.050,0.0,0.012,0.043,0.01,0.02,-1,0.135,5.32315,20.760
4,Brandega-17919,Back to School,Botann's,12345-90005-109,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,-0.023,0.0,0.012,0.043,-0.10,0.02,1,-0.048,4.37016,45.696

In [50]:
#Make sure that size is always positive, create a new variable called price_size convert size to a numeric value
df_total4.SIZE = df_total4.SIZE.astype(float).fillna(0.0)


df_total4['PRICE_SIZE']=df_total4['PRICE_R']*df_total4['SIZE']


df_total4.SIZE.value_counts(dropna = False).sort_index()

20.0    77464
32.0    77464
64.0    77464
Name: SIZE, dtype: int64

In [51]:
#create a dummy variable for ice cream
df_total4['SIZE_16'] = np.where(df_total4['SIZE'] == 16, 1, 0)
df_total4['SIZE_16_PRICE']=df_total4['SIZE_16']*df_total4['PRICE']
df_total4.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,PRICE,...,Promo_Name_R,GROUP_R,month_R,randNumCol,TOTAL_R,PRICE_R,UNITS_R,PRICE_SIZE,SIZE_16,SIZE_16_PRICE
0,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,0.043,-0.10,0.02,1,-0.025,4.27425,46.800,85.4850,0,0.0
1,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,0.043,0.01,0.02,1,0.085,4.29135,26.040,85.8270,0,0.0
2,Brandega-17919,Back to School,Botann's,12345-79914-108,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,0.043,-0.10,0.02,1,0.025,4.06575,49.200,81.3150,0,0.0
3,Brandega-17919,Back to School,Botann's,12345-79914-108,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.69,...,0.043,0.01,0.02,-1,0.135,5.32315,20.760,106.4630,0,0.0
4,Brandega-17919,Back to School,Botann's,12345-90005-109,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,4.17,...,0.043,-0.10,0.02,1,-0.048,4.37016,45.696,87.4032,0,0.0

In [52]:
#bring in the stats library to build the model
import statsmodels.api as sm  
#scikit learn is another library that you could use.  Its focus is more on prediction.  This library is more focused on understanding why and how certain variables impact your target.  Which is quantity in this case

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [53]:
df_total4=df_total4.drop(['PRICE'], axis=1)

In [54]:
v = df_total4[['PRICE_R','TOTAL_R','SIZE','PRICE_SIZE','UNITS_R']]
w = df_total4[['PRICE_R','TOTAL_R','SIZE','PRICE_SIZE','UNITS_R']]
x = df_total4[['PRICE_R','TOTAL_R','SIZE','PRICE_SIZE','UNITS_R']]
y = df_total4[['PRICE_R','TOTAL_R','SIZE','PRICE_SIZE','UNITS_R']]
z = df_total4[['PRICE_R','TOTAL_R','SIZE','PRICE_SIZE','UNITS_R']]

In [55]:
pricev = pd.DataFrame((v['PRICE_R']*0.95))
pricew = pd.DataFrame((w['PRICE_R']*0.85))
pricey = pd.DataFrame((y['PRICE_R']*0.90))
pricez= pd.DataFrame((z['PRICE_R']*0.80))

qv = pd.DataFrame((v['UNITS_R']*1.05))
qw = pd.DataFrame((w['UNITS_R']*1.15))
qy = pd.DataFrame((y['UNITS_R']*1.10))
qz= pd.DataFrame((z['UNITS_R']*1.20))

In [56]:
df_total4.head()

,Promo_ID,Promo_Name,Retailer_Name,Retailer_Store_ID,Product_Group_ID,Product_Unit_UPC,Product_Brand,Product_Brand_Category_Desc,Product_Unit_Description,TPP_Type,...,Promo_Name_R,GROUP_R,month_R,randNumCol,TOTAL_R,PRICE_R,UNITS_R,PRICE_SIZE,SIZE_16,SIZE_16_PRICE
0,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,TPR,...,0.043,-0.10,0.02,1,-0.025,4.27425,46.800,85.4850,0,0.0
1,Brandega-17919,Back to School,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,N,...,0.043,0.01,0.02,1,0.085,4.29135,26.040,85.8270,0,0.0
2,Brandega-17919,Back to School,Botann's,12345-79914-108,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,TPR,...,0.043,-0.10,0.02,1,0.025,4.06575,49.200,81.3150,0,0.0
3,Brandega-17919,Back to School,Botann's,12345-79914-108,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,N,...,0.043,0.01,0.02,-1,0.135,5.32315,20.760,106.4630,0,0.0
4,Brandega-17919,Back to School,Botann's,12345-90005-109,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,TPR,...,0.043,-0.10,0.02,1,-0.048,4.37016,45.696,87.4032,0,0.0

In [57]:
#create multiple price points and quantities for each campaign

v=v.drop(['PRICE_R','UNITS_R'], axis=1)
v = pd.concat([v, pricev,qv], axis=1)
v['PRICE_POINT']='V'
stuff=df_total4[['Promo_ID','Retailer_Store_ID','Product_Unit_UPC','TPP_Type']]
v = pd.concat([v, stuff], axis=1)

In [58]:

w=w.drop(['PRICE_R','UNITS_R'], axis=1)
w = pd.concat([w, pricew,qw], axis=1)
w['PRICE_POINT']='W'

w = pd.concat([w, stuff], axis=1)

y=y.drop(['PRICE_R','UNITS_R'], axis=1)
y = pd.concat([y, pricey,qy], axis=1)
y['PRICE_POINT']='Y'
y = pd.concat([y, stuff], axis=1)

z=z.drop(['PRICE_R','UNITS_R'], axis=1)
z = pd.concat([z, pricez,qz], axis=1)
z['PRICE_POINT']='Z'
z = pd.concat([z, stuff], axis=1)

x['PRICE_POINT']='X'
x = pd.concat([x, stuff], axis=1)

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [59]:
xxx=pd.concat([v,w,x,y,z],axis=0)

In [60]:
#build the ols model

independent=xxx[['PRICE_R','TOTAL_R','SIZE','PRICE_SIZE']]
P=xxx['PRICE_POINT']
stuff=xxx[['Promo_ID','Retailer_Store_ID','Product_Unit_UPC','TPP_Type']]

independent = sm.add_constant(independent, prepend=False)

dependent=xxx['UNITS_R']

In [61]:
mod = sm.OLS(dependent, independent)

In [62]:
res = mod.fit()

In [63]:
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                UNITS_R   R-squared:                       0.609
Model:                            OLS   Adj. R-squared:                  0.609
Method:                 Least Squares   F-statistic:                 4.533e+05
Date:                Thu, 17 Jan 2019   Prob (F-statistic):               0.00
Time:                        18:05:40   Log-Likelihood:            -4.2643e+06
No. Observations:             1161960   AIC:                         8.529e+06
Df Residuals:                 1161955   BIC:                         8.529e+06
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
PRICE_R       -6.3912      0.022   -294.997      0.000      -6.434      -6.349
TOTAL_R     -135.9133      0.137   -990.082      0.000    -136.182    -135.644
SIZE          -0.7840      0.002   -477.708      0.000      -0.787      -0.781
PRICE_SIZE     0.1428      0.001    263.044      0.000       0.142       0.144
const         74.8680      0.076    987.249      0.000      74.719      75.017
==============================================================================
Omnibus:                   252566.687   Durbin-Watson:                   1.761
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           516142.197
Skew:                           1.297   Prob(JB):                         0.00
Kurtosis:                       4.983   Cond. No.                     2.72e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.72e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [64]:
ypred = pd.DataFrame(res.predict(independent))
ypred.columns = ['P_UNITS']

In [65]:
model_output=pd.concat([ypred,independent,stuff,P], axis=1)
model_output.head()

,P_UNITS,PRICE_R,TOTAL_R,SIZE,PRICE_SIZE,const,Promo_ID,Retailer_Store_ID,Product_Unit_UPC,TPP_Type,PRICE_POINT
0,48.844695,4.060537,-0.025,20.0,85.4850,1.0,Brandega-17919,12345-94249-107,66335-40120,TPR,V
1,33.839252,4.076783,0.085,20.0,85.8270,1.0,Brandega-17919,12345-94249-107,66335-40120,N,V
2,42.719347,3.862462,0.025,20.0,81.3150,1.0,Brandega-17919,12345-79914-108,66335-40120,TPR,V
3,23.726394,5.056992,0.135,20.0,106.4630,1.0,Brandega-17919,12345-79914-108,66335-40120,N,V
4,51.662355,4.151652,-0.048,20.0,87.4032,1.0,Brandega-17919,12345-90005-109,66335-40120,TPR,V

In [66]:
df_main_stuff=df_total4.drop(['PRICE_R','TOTAL_R','SIZE','PRICE_SIZE'], axis=1)
df_main_stuff.columns

Index(['Promo_ID', 'Promo_Name', 'Retailer_Name', 'Retailer_Store_ID',
       'Product_Group_ID', 'Product_Unit_UPC', 'Product_Brand',
       'Product_Brand_Category_Desc', 'Product_Unit_Description', 'TPP_Type',
       'TPP_Start', 'TPP_End', 'Product_Units_Per_Case',
       'Product_CPG_COGS_Price', 'CASES', 'GROUP', 'UNITS', 'date', 'year',
       'month', 'Retailer_R', 'PRODUCT_GROUP_ID_R', 'Product_Unit_UPC_R',
       'Promo_Name_R', 'GROUP_R', 'month_R', 'randNumCol', 'UNITS_R',
       'SIZE_16', 'SIZE_16_PRICE'],
      dtype='object')

In [67]:
df_main_stuff=df_main_stuff.drop_duplicates(subset=['Promo_ID','Retailer_Store_ID','Product_Unit_UPC','TPP_Type'], keep='first', inplace=False)
df_main_stuff.shape

(232392, 30)

In [68]:
df_total5 =model_output.merge(df_main_stuff, on=['Promo_ID','Retailer_Store_ID','Product_Unit_UPC','TPP_Type'], how='inner')
df_total5.shape

(1161960, 37)

In [69]:
df_total5.describe()

,P_UNITS,PRICE_R,TOTAL_R,SIZE,PRICE_SIZE,const,Product_Units_Per_Case,Product_CPG_COGS_Price,CASES,UNITS,...,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R,GROUP_R,month_R,randNumCol,UNITS_R,SIZE_16,SIZE_16_PRICE
count,1.161960e+06,1.161960e+06,1.161960e+06,1.161960e+06,1.161960e+06,1161960.0,1.161960e+06,1.161960e+06,1.161960e+06,1.161960e+06,...,1.161960e+06,1.161960e+06,1.161960e+06,1.161960e+06,1161960.000,1.161960e+06,1.161960e+06,1.161960e+06,1161960.0,1161960.0
mean,3.162231e+01,4.262024e+00,5.871881e-02,3.866667e+01,1.560422e+02,1.0,1.800000e+01,3.623333e+00,1.625000e+00,2.875000e+01,...,1.227316e-02,1.100000e-02,1.869565e-02,4.175000e-02,-0.045,2.000000e-02,-5.249750e-04,2.874755e+01,0.0,0.0
std,1.186449e+01,2.185708e+00,6.696817e-02,1.857119e+01,6.967454e+01,0.0,4.898982e+00,1.767944e+00,7.534645e-01,1.352544e+01,...,2.681864e-02,8.981466e-03,2.213157e-02,1.089438e-02,0.055,3.566524e-13,1.000000e+00,1.366363e+01,0.0,0.0
min,1.012859e-01,1.359864e+00,-1.060000e-01,2.000000e+01,7.116240e+01,1.0,1.200000e+01,1.590000e+00,1.000000e+00,1.200000e+01,...,-3.000000e-02,0.000000e+00,-2.700000e-02,3.100000e-02,-0.100,2.000000e-02,-1.000000e+00,9.408000e+00,0.0,0.0
25%,2.266945e+01,2.010216e+00,4.000000e-03,2.000000e+01,9.511320e+01,1.0,1.200000e+01,1.590000e+00,1.000000e+00,1.800000e+01,...,-1.100000e-02,0.000000e+00,3.000000e-03,3.325000e-02,-0.100,2.000000e-02,-1.000000e+00,1.859400e+01,0.0,0.0
50%,3.132722e+01,3.914475e+00,5.900000e-02,3.200000e+01,1.272960e+02,1.0,1.800000e+01,3.380000e+00,1.500000e+00,2.400000e+01,...,1.100000e-02,1.100000e-02,2.100000e-02,3.850000e-02,-0.045,2.000000e-02,-1.000000e+00,2.438400e+01,0.0,0.0
75%,3.980903e+01,6.174600e+00,1.140000e-01,6.400000e+01,2.255053e+02,1.0,2.400000e+01,5.900000e+00,2.000000e+00,3.900000e+01,...,3.600000e-02,2.200000e-02,3.700000e-02,4.700000e-02,0.010,2.000000e-02,1.000000e+00,4.026600e+01,0.0,0.0
max,6.556712e+01,9.991800e+00,2.200000e-01,6.400000e+01,3.197376e+02,1.0,2.400000e+01,5.900000e+00,4.000000e+00,5.400000e+01,...,5.900000e-02,2.200000e-02,5.800000e-02,5.900000e-02,0.010,2.000000e-02,1.000000e+00,5.994000e+01,0.0,0.0

In [70]:
df_total5.loc[df_total5['P_UNITS'] < 0, 'P_UNITS'] = 0
df_total5.describe()

,P_UNITS,PRICE_R,TOTAL_R,SIZE,PRICE_SIZE,const,Product_Units_Per_Case,Product_CPG_COGS_Price,CASES,UNITS,...,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R,GROUP_R,month_R,randNumCol,UNITS_R,SIZE_16,SIZE_16_PRICE
count,1.161960e+06,1.161960e+06,1.161960e+06,1.161960e+06,1.161960e+06,1161960.0,1.161960e+06,1.161960e+06,1.161960e+06,1.161960e+06,...,1.161960e+06,1.161960e+06,1.161960e+06,1.161960e+06,1161960.000,1.161960e+06,1.161960e+06,1.161960e+06,1161960.0,1161960.0
mean,3.162231e+01,4.262024e+00,5.871881e-02,3.866667e+01,1.560422e+02,1.0,1.800000e+01,3.623333e+00,1.625000e+00,2.875000e+01,...,1.227316e-02,1.100000e-02,1.869565e-02,4.175000e-02,-0.045,2.000000e-02,-5.249750e-04,2.874755e+01,0.0,0.0
std,1.186449e+01,2.185708e+00,6.696817e-02,1.857119e+01,6.967454e+01,0.0,4.898982e+00,1.767944e+00,7.534645e-01,1.352544e+01,...,2.681864e-02,8.981466e-03,2.213157e-02,1.089438e-02,0.055,3.566524e-13,1.000000e+00,1.366363e+01,0.0,0.0
min,1.012859e-01,1.359864e+00,-1.060000e-01,2.000000e+01,7.116240e+01,1.0,1.200000e+01,1.590000e+00,1.000000e+00,1.200000e+01,...,-3.000000e-02,0.000000e+00,-2.700000e-02,3.100000e-02,-0.100,2.000000e-02,-1.000000e+00,9.408000e+00,0.0,0.0
25%,2.266945e+01,2.010216e+00,4.000000e-03,2.000000e+01,9.511320e+01,1.0,1.200000e+01,1.590000e+00,1.000000e+00,1.800000e+01,...,-1.100000e-02,0.000000e+00,3.000000e-03,3.325000e-02,-0.100,2.000000e-02,-1.000000e+00,1.859400e+01,0.0,0.0
50%,3.132722e+01,3.914475e+00,5.900000e-02,3.200000e+01,1.272960e+02,1.0,1.800000e+01,3.380000e+00,1.500000e+00,2.400000e+01,...,1.100000e-02,1.100000e-02,2.100000e-02,3.850000e-02,-0.045,2.000000e-02,-1.000000e+00,2.438400e+01,0.0,0.0
75%,3.980903e+01,6.174600e+00,1.140000e-01,6.400000e+01,2.255053e+02,1.0,2.400000e+01,5.900000e+00,2.000000e+00,3.900000e+01,...,3.600000e-02,2.200000e-02,3.700000e-02,4.700000e-02,0.010,2.000000e-02,1.000000e+00,4.026600e+01,0.0,0.0
max,6.556712e+01,9.991800e+00,2.200000e-01,6.400000e+01,3.197376e+02,1.0,2.400000e+01,5.900000e+00,4.000000e+00,5.400000e+01,...,5.900000e-02,2.200000e-02,5.800000e-02,5.900000e-02,0.010,2.000000e-02,1.000000e+00,5.994000e+01,0.0,0.0

In [71]:
df_total5=df_total5.rename(index=str, columns={"PRICE_R": "PRICE"})

#tips = df_total5.sort_values(['Promo_ID', 'Retailer_Store_ID', 'Product_Unit_UPC'])
df_total5.head()

,P_UNITS,PRICE,TOTAL_R,SIZE,PRICE_SIZE,const,Promo_ID,Retailer_Store_ID,Product_Unit_UPC,TPP_Type,...,Retailer_R,PRODUCT_GROUP_ID_R,Product_Unit_UPC_R,Promo_Name_R,GROUP_R,month_R,randNumCol,UNITS_R,SIZE_16,SIZE_16_PRICE
0,48.844695,4.060537,-0.025,20.0,85.485,1.0,Brandega-17919,12345-94249-107,66335-40120,TPR,...,0.0,0.0,0.012,0.043,-0.1,0.02,1,46.8,0,0.0
1,51.576473,3.633112,-0.025,20.0,85.485,1.0,Brandega-17919,12345-94249-107,66335-40120,TPR,...,0.0,0.0,0.012,0.043,-0.1,0.02,1,46.8,0,0.0
2,47.478806,4.274250,-0.025,20.0,85.485,1.0,Brandega-17919,12345-94249-107,66335-40120,TPR,...,0.0,0.0,0.012,0.043,-0.1,0.02,1,46.8,0,0.0
3,50.210584,3.846825,-0.025,20.0,85.485,1.0,Brandega-17919,12345-94249-107,66335-40120,TPR,...,0.0,0.0,0.012,0.043,-0.1,0.02,1,46.8,0,0.0
4,52.942362,3.419400,-0.025,20.0,85.485,1.0,Brandega-17919,12345-94249-107,66335-40120,TPR,...,0.0,0.0,0.012,0.043,-0.1,0.02,1,46.8,0,0.0

In [72]:
#keep the relevant variables
df_total5 = df_total5[['Promo_ID',
 'Promo_Name',
 'PRICE_POINT',
'Retailer_Name',
 'Retailer_Store_ID',
 'Product_Group_ID',
 'Product_Unit_UPC',
 'Product_Brand',
 'Product_Brand_Category_Desc',
 'Product_Unit_Description',
 'PRICE',
 'TPP_Type',
 'TPP_Start',
 'TPP_End',
 'Product_Units_Per_Case',
 'Product_CPG_COGS_Price',
 'SIZE',
 'CASES',
 'GROUP',
 'UNITS',     
 'P_UNITS']]

In [73]:
#capitalize the field names to load in dash
df_total5=df_total5.rename(str.upper, axis='columns')

In [74]:
df_total5.PRICE_POINT.value_counts(dropna = False).sort_index()

V    232392
W    232392
X    232392
Y    232392
Z    232392
Name: PRICE_POINT, dtype: int64

In [75]:
#De-Dup the file
df_total5=df_total5.drop_duplicates(subset=['PROMO_ID','RETAILER_STORE_ID','PRODUCT_UNIT_UPC','GROUP','PRICE_POINT'], keep='first', inplace=False)
df_total5.shape
df_total5.head()

,PROMO_ID,PROMO_NAME,PRICE_POINT,RETAILER_NAME,RETAILER_STORE_ID,PRODUCT_GROUP_ID,PRODUCT_UNIT_UPC,PRODUCT_BRAND,PRODUCT_BRAND_CATEGORY_DESC,PRODUCT_UNIT_DESCRIPTION,...,TPP_TYPE,TPP_START,TPP_END,PRODUCT_UNITS_PER_CASE,PRODUCT_CPG_COGS_PRICE,SIZE,CASES,GROUP,UNITS,P_UNITS
0,Brandega-17919,Back to School,V,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,...,TPR,2019-08-26,2019-09-04,24.0,3.38,20.0,2.0,ONSALE,48.0,48.844695
1,Brandega-17919,Back to School,W,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,...,TPR,2019-08-26,2019-09-04,24.0,3.38,20.0,2.0,ONSALE,48.0,51.576473
2,Brandega-17919,Back to School,X,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,...,TPR,2019-08-26,2019-09-04,24.0,3.38,20.0,2.0,ONSALE,48.0,47.478806
3,Brandega-17919,Back to School,Y,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,...,TPR,2019-08-26,2019-09-04,24.0,3.38,20.0,2.0,ONSALE,48.0,50.210584
4,Brandega-17919,Back to School,Z,Botann's,12345-94249-107,GD-F-V-S-20,66335-40120,Garden Delights,Garden Delights Vegetables Simple 20 oz,Garden Delights Mixed Vegetables 20 oz,...,TPR,2019-08-26,2019-09-04,24.0,3.38,20.0,2.0,ONSALE,48.0,52.942362

In [76]:

# @hidden_cell
credentials_1 = {
  'database':'BLUDB',
  'password':"""xxxxxxxxxxxxx""",
  'sg_service_url':'https://sgmanager.ng.bluemix.net',
  'host':'dashdb-entry-yp-dal09-08.services.dal.bluemix.net',
  'username':'dash10112',
  'url':'https://undefined'
}

In [77]:
df_load=df_total5

In [78]:
#load records to dashdb

import ibmdbpy
from ibmdbpy import IdaDataBase
idadb = idadb = IdaDataBase(dsn="DASHDB;Database=BLUDB;Hostname=" + credentials_1["host"] + ";PROTOCOL=TCPIP;UID=" + credentials_1["username"] + ";PWD=" + credentials_1["password"])

In [79]:
 idadb.as_idadataframe(df_load, "VEGETABLES_FINAL_PRODUCTION",clear_existing = True)

DataFrame will be splitted into 3058 chunks. (380 rows per chunk)
Uploaded: 3058/3058... [DONE]

In [80]:
#spark_df = sqlContext.createDataFrame(df_total5)

In [81]:
#### this inserts records


#from ingest.Connectors import Connectors

#dashdbsaveoption = {
 #                    Connectors.DASHDB.HOST              : 'dashdb-entry-yp-dal09-08.services.dal.bluemix.net',
  #                   Connectors.DASHDB.DATABASE          : 'BLUDB',
   #                  Connectors.DASHDB.USERNAME          : 'dash10112',
    #                 Connectors.DASHDB.PASSWORD          : '-rMyl8IIE1~n',
     #                Connectors.DASHDB.TARGET_TABLE_NAME : 'ICE_CREAM',
      #               Connectors.DASHDB.TARGET_WRITE_MODE : 'merge' }

#spark_df = spark_df.write.format("com.ibm.spark.discover").options(**dashdbsaveoption).save()

In [82]:
#### this deletes then inserts records


#from ingest.Connectors import Connectors

#dashdbsaveoption = {
 #                    Connectors.DASHDB.HOST              : 'dashdb-entry-yp-dal09-08.services.dal.bluemix.net',
  #                   Connectors.DASHDB.DATABASE          : 'BLUDB',
   #                  Connectors.DASHDB.USERNAME          : 'dash10112',
    #                 Connectors.DASHDB.PASSWORD          : '-rMyl8IIE1~n',
     #                Connectors.DASHDB.TARGET_TABLE_NAME : 'DASH10112.ICE_CREAM',
      #               Connectors.DASHDB.TARGET_TABLE_ACTION : 'replace' }

#spark_df = spark_df.write.format("com.ibm.spark.discover").options(**dashdbsaveoption).save()

In [83]:
#This reads records


#from ingest.Connectors import Connectors
#from pyspark.sql import SQLContext
#sqlContext = SQLContext(sc)

#dashDBloadOptions = { Connectors.DASHDB.HOST              : 'dashdb-entry-yp-dal09-08.services.dal.bluemix.net',
 #                     Connectors.DASHDB.DATABASE          : 'BLUDB',
  #                    Connectors.DASHDB.USERNAME          : 'dash10112',
   #                   Connectors.DASHDB.PASSWORD          : '-rMyl8IIE1~n',
    #                  Connectors.DASHDB.SOURCE_TABLE_NAME : 'ICE_CREAM'}

#dashdbDF = sqlContext.read.format("com.ibm.spark.discover").options(**dashDBloadOptions).load()
#dashdbDF.printSchema()
#dashdbDF.show()

In [84]:
#abcd=dashdbDF.toPandas()

In [85]:
#abcd.shape
#abcd.info()